Planner_add command implementation
CS2113-AY1819S2-T09-1/main pull request #109
Opened 2019-03-21 02:46 UTC by WendyBaiYunwei

2019-03-21 05:44 UTC, lycjackie requested changes
Some comments based on user testing.

1.  After a successful add. The display panel on the right is not refreshing.
2. `planner_add` help message did not reflect ` ` between `y/` and `s/`
3. `planner_add code/CS2040C y/1 s/2` lead to an runtime error

i.e. `planner_add code/CS1231 y/1 s/1` is okay but 
`planner_add code/CS2040C y/1 s/2` is not

2019-03-21 12:32 UTC, lycjackie requested changes

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> -
Unnecessary deletion of line

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/DegreePlannerList.java
> +    public boolean hasDegreePlannerModule(DegreePlanner plannerModules) {
Could have a better variable name instead of `plannerModules`

`plannerModules` normally suggest a `list` of something.

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/DegreePlannerList.java
> +    public void addDegreePlannerModule(DegreePlanner p) {
Likewise, single variable name is not recommended.

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/Model.java
> +    boolean hasDegreePlannerModule(DegreePlanner plannerModules);
As mention previously

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/Model.java
> +    void addDegreePlannerModule(DegreePlanner plannerModules);
As mention previously

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/ModelManager.java
> +    public boolean hasDegreePlannerModule(DegreePlanner plannerModules) {
As mention previously

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> -
Unnecessary deletion of line.

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +        int location = 0;
if `location = 0` from the start, even if the checks fail. 

This will still return `location = 0` which can be a valid index.

@chyeo You also have this mistake. It was my bad that I did not spot it during the review.

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/model/planner/Year.java
> +
Unnecessary line added

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/storage/Storage.java
> +
Unnecessary line added

Try not to make any modification to a file which this PR is not related.

2019-03-21 12:32 UTC, lycjackie commented on src/main/java/seedu/address/storage/StorageManager.java
> +
Unnecessary line added

2019-03-21 12:32 UTC, lycjackie commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +        public boolean hasDegreePlannerModule(DegreePlanner plannerModules) {
As mention previously, do take note of all your variable name.

2019-03-21 12:32 UTC, lycjackie commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +            return false;
Since this is a test class

Is either you implement it correctly or you leave it empty for the moment.

By returning a static value, this is a bad impression that your code is running as expected
if there is any test cases that use this method.

2019-03-21 12:38 UTC, lycjackie commented
After the latest build, here some stuff I found.

1. Able to add non-existence module into the planner.  
2. The display panel is still not updating after the command. 
- Look at `edit` command for example.

2019-03-25 09:20 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> -
there will be a checkstyle error if i delete the line o.o

2019-03-25 09:21 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> -
don't delete*

2019-03-25 09:24 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> -
line resumed

2019-03-25 09:24 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> -
there will be a checkstyle error if I don't delete the line

2019-03-25 13:40 UTC, WendyBaiYunwei commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +            return false;
I added a toDo comment and am planning to implement the test afterwards. is it ok? according to tutors one pr doesn't need to contain everything. PR can be small o.o

2019-03-25 13:41 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +        int location = 0;
location variable is required to get initialized. Correct me if I'm wrong. I don't think this part will cause problem because we already checked that year and sem are valid number. thus the returned index will be valid as well.

2019-03-25 16:36 UTC, lycjackie requested changes

2019-03-25 16:36 UTC, lycjackie commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        if (!model.existingPlannerModules(toAdd, model)) {
You might want to reference the below code to improve on this method.
https://github.com/CS2113-AY1819S2-T09-1/main/blob/7d55c1a32c117cea8ca5548763c6d358b183cfb7/src/main/java/seedu/address/logic/commands/RequirementAddCommand.java#L63-L65

This does not really make sense that an object `model` take in itself as a parameter...

2019-03-25 16:36 UTC, lycjackie commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +import static seedu.address.logic.commands.RequirementAddCommand.MESSAGE_MODULE_DOES_NOT_EXIST;
Why are you using `RequirementAddCommand` message for your own planner?

You might want to write your own message.

2019-03-25 16:36 UTC, lycjackie commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    public boolean containsModules(DegreePlanner toCheck) {
Might want to consider how `UniqueRequirementCategory.java` implements this...

https://github.com/CS2113-AY1819S2-T09-1/main/blob/7d55c1a32c117cea8ca5548763c6d358b183cfb7/src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java#L49-L52

This allow our code base to be consistent.

2019-03-25 16:36 UTC, lycjackie commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> +            return false;
Yes okay. Do remember to update your TODO

2019-03-25 16:36 UTC, lycjackie commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +        int location = 0;
Yes, you're right that location variable is required for this.

However, if you feel that there is no logic bug in this. Then I'm okay with this. 

@Creastery did mention in our chat on why using location is bad too btw. 

But do bear in mind that if a bug is found regarding this. You might still need to fix
this again...

2019-03-25 16:38 UTC, lycjackie commented
I have clone down your current branch and tried running the command.

I seem to be encountering errors by inputting

`planner_add code/CS1231 year/1 sem/1`

Do try to get this fix too..

2019-03-26 12:09 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/AddressBook.java
> -
Line deleted because it caused checkstyle error

2019-03-26 12:13 UTC, WendyBaiYunwei commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> -
there are a few trailing white space checkstyle issues. perhaps it is my configuration problem. But can we ignore the extra(?) deletion of the line if it does not affect the code quality?

2019-03-27 02:05 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> -
line resumed

2019-03-27 02:06 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/AddressBook.java
> -
line resumed

2019-03-27 02:06 UTC, WendyBaiYunwei commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> -
line resumed

2019-03-27 08:43 UTC, Letm3through requested changes
Please consider making following changes to the way `Planner_add` is implemented.
In addition, you should have your own `PlannerAddCommandTest`.
Also, please remove irrelevant methods u added in `AddCommandTest` if there is after making changes. 
Thanks you.

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/AddressBook.java
> -
May I know what is the purpose of removing this line?
I think you should not remove this line.

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/AddressBook.java
> +    }
Please add a blank line between like the rest

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/AddressBook.java
> +    /**
Please add the blank line between as stated above

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/AddressBook.java
> +    }
Please add the blank line between as stated above

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/Model.java
> +     * {@code plannerModule} must not already exist in the address book.
Do you mean `plannerModules`?

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/planner/Semester.java
> +            "Semester should be either 1 or 2, in format sem/1 or sem/2.";
Try to edit `Semester should be either 1 or 2, in format sem/1 or sem/2.` to make it consistent with other constraints related messages.

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/planner/Year.java
> +            "Year should be in y/x format, where x is an integer greater than 0 and smaller than 5.";
As we discuss, we will be using `year/` instead of `y/`. 
Please amend this part. 
Also, I think it will be better to use `between` instead of saying `greater ....` or `less` instead of `smaller`

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +     * Adds the new modules to the particular degree planner with matching year and semester.
Perhaps, you could be more clear by rephrasing the sentence instead of just stating `new modules`

2019-03-27 08:43 UTC, Letm3through commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +     * Returns true if the modules to add are contained inside the entire degree planner.
Do you mean any one of the modules? Might want to state it more clearly.
Also as mentioned by Jackie, you may want to change the name of the method to be consistent.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    /**
I think you shouldn't implement the `planner_add` method this way.
You should implement in the manner where `planner_add` edit degree planner by setting `new` degree planner based on modules requested to be added to the degree planner. 
This way `planner_delete` will able to utilize the same methods too.
In addition, you would not need the method `location` for it.
If you are not sure, please refer to how others(e.g. `requirement_add`) are implemented.
Please try to make changes.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    public void addModules(DegreePlanner toAdd) {
Refer to the abovementioned comment at line at https://github.com/CS2113-AY1819S2-T09-1/main/blob/f8a31042aecb88072c9a9c220ab4193f5321229e/src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java#L59

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/model/ModelManager.java
> +    public boolean hasDegreePlannerModules(DegreePlanner plannerModules) {
Is this necessary to be implemented here? I think you can directly implement this in `PlannerAddCommand`.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/model/ModelManager.java
> +    @Override
Same comment as mentioned above.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/model/ModelManager.java
> +    /**
Same comment as mentioned above.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/model/Model.java
> +    boolean hasDegreePlannerModules(DegreePlanner plannerModules);
Refer to the ModelManager comment at line https://github.com/CS2113-AY1819S2-T09-1/main/blob/f8a31042aecb88072c9a9c220ab4193f5321229e/src/main/java/seedu/address/model/ModelManager.java#L297

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/model/Model.java
> +    void addDegreePlannerModules(DegreePlanner plannerModules);
Refer to the comment at line https://github.com/CS2113-AY1819S2-T09-1/main/blob/f8a31042aecb88072c9a9c220ab4193f5321229e/src/main/java/seedu/address/model/ModelManager.java#L311

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a module to the degree planner. "
I realised you are trying to add modules. If then, please correct this `COMMAND_WORD`

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_SUCCESS = "New module added: %1$s";
What if you are adding more than one module?
You may want to include the case too.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "This module already exists in the degree planner";
What are more than one module existing in the degree planner?

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds modules to degree planner. "
You may want to edit it to `Adds modules to a degree planner.` since you are adding on the particular degree planner

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_SUCCESS = "New modules added to degree planner: %1$s";
What if you are adding just one module?
You may want to include the case too.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "Some of the module codes do"
You used `modules` and here you are using `module codes`.
You may want to edit to be consistent.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "Some of the modules already exist in degree planner";
What if only one module exists? You may want to include that.

2019-03-27 08:43 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public CommandResult execute(Model model, CommandHistory history) throws CommandException {
May want to better implement this part. Refer to the comment at line https://github.com/CS2113-AY1819S2-T09-1/main/blob/f8a31042aecb88072c9a9c220ab4193f5321229e/src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java#L59

2019-03-27 09:17 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    /**
Thank you for all the feedback. I have implemented planner_delete locally, and it takes in different parameter (a set of codes). Due to different format, it will not reuse planner_add implementation. (as planner_delete does not specify the year and sem for convenience reason)

2019-03-27 09:19 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    /**
the code quality is assessed individually, thus the quality of my code will not affect the team. Still, I welcome feedback because I also want to improve. But just mentioning about the assessment in case you do not know.

2019-03-27 09:26 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    /**
The location method I will just leave it at least for now because of a couple of reasons. I need to implement co-requisite and write for test. and I do not have much time left. Besides, I do not want my code to be identical as CH's code because I cannot think of his method myself.
Please also note that consistency among group members are not assessed as well.

2019-03-27 09:39 UTC, WendyBaiYunwei commented
> Please consider making following changes to the way `Planner_add` is implemented.
> In addition, you should have your own `PlannerAddCommandTest`.
> Also, please remove irrelevant methods u added in `AddCommandTest` if there is after making changes.
> Thanks you.

Thank you so much for your advice. the extra tests have been removed and new tests will be submitted through another PR.

2019-03-27 09:43 UTC, WendyBaiYunwei commented
Please note that after I remove the extra tests, appveyor check fails. Please let me know ASAP if you need me to resume the tests or make any other changes. Thank you!

2019-03-27 10:05 UTC, truegitnovice commented
@WendyBaiYunwei What I meant above was to `remove irrelevant methods u added in AddCommandTest if there is after making changes` which means if you are removing methods (for e.g. addDegreePlannerModules) in the process of changing implementation of `planner_add`, please remember to remove this method in the `AddCommandTest`. I mentioned this part because I believe that you can have better implementation of `planner_add` and during the process of modification, you may remove some methods you added in like `addDegreePlannerModules`.
Sorry for making this unclear.

2019-03-27 11:26 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/AddressBook.java
> -
line resumed

2019-03-27 11:27 UTC, truegitnovice commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    /**
> Besides, I do not want my code to be identical as CH's code because I cannot think of his method myself.
This method you are using is just identical to the version of Requirement Add at #82  before the bug fix in #112:
https://github.com/chyeo/main/blob/576f6049c23c52863ce82a5fc5c9d6e0f4d46d30/src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java#L53-L63
So I am not sure why you are mentioning the point. 
I am still not sure why you have to use locate the degree planner in this manner.
I thought we have discussed about this matter previously in the group.
May I know what is actually changed in this method after the discussion so that I have clearer idea about this?

2019-03-28 15:25 UTC, Creastery commented
There are already two reviewers, which have requested changes previously.
You should fix them before asking them for a review.

2019-03-28 21:53 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a module to the degree planner. "
planner means the modules to add are related to the degree planner. It's meant to differentiate between normal adding and adding to planner. I thought we already agreed on the name. if i make it "module_add", it can be misleading as ppl don't know whether it's for planner?

2019-03-28 21:53 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_SUCCESS = "New module added: %1$s";
fixed

2019-03-28 21:54 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "This module already exists in the degree planner";
fixed

2019-03-28 21:54 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/AddressBook.java
> +    }
fixed

2019-03-28 21:55 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/AddressBook.java
> +    /**
fixed

2019-03-28 21:55 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/AddressBook.java
> +    }
fixed

2019-03-28 21:55 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/Model.java
> +     * {@code plannerModule} must not already exist in the address book.
fixed

2019-03-28 21:57 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/Semester.java
> +            "Semester should be either 1 or 2, in format sem/1 or sem/2.";
fixed

2019-03-28 21:59 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +     * Adds the new modules to the particular degree planner with matching year and semester.
fixed

2019-03-28 22:00 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +     * Returns true if the modules to add are contained inside the entire degree planner.
fixed

2019-03-28 22:00 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/Year.java
> +            "Year should be in y/x format, where x is an integer greater than 0 and smaller than 5.";
fixed

2019-03-28 22:55 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/planner/UniqueDegreePlannerList.java
> +    /**
I mean I could think of the location method, but stream was not something I could think of. I have modified the implementation.

2019-03-28 23:02 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/ModelManager.java
> +    public boolean hasDegreePlannerModules(DegreePlanner plannerModules) {
fixed

2019-03-29 12:05 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds modules to degree planner. "
fixed

2019-03-29 12:05 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_SUCCESS = "New modules added to degree planner: %1$s";
fixed

2019-03-29 12:05 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "Some of the module codes do"
fixed

2019-03-29 12:05 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "Some of the modules already exist in degree planner";
fixed

2019-03-29 12:05 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public CommandResult execute(Model model, CommandHistory history) throws CommandException {
fixed

2019-03-30 05:12 UTC, Letm3through requested changes
Please look through the codes one more time before adding `status.ToReview` so that we don't have to review multiple times on similar issues.
Furthmore, please resolve conversation when it is resolved so that it is clear which issue you have resolved.

2019-03-30 05:12 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        if (codesToAdd.stream().anyMatch(code -> !model.existingModuleListModules(code))) {
Is there need to implement method for this and not use the pre-existing one in the `moduleList`?

2019-03-30 05:26 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        if (codesToAdd.stream().anyMatch(code -> !model.existingModuleListModules(code))) {
fixed

2019-03-30 06:59 UTC, lycjackie commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +            + PREFIX_SEMESTER + "SEMESTER";
Perhaps you might want to consider adding examples on your command usage?

This would help the users to have a better idea on what to input

Pretty useful for tester too when we can just copy and paste the examples.

2019-03-30 12:31 UTC, lycjackie commented
The `Logic` part of the code generally looks okay. 

I will request a review from @Creastery on the `Model` part.

I guess should be ready to merge soon after he takes a look on the `Model`

Do remember to add in your unit tests for your functionality.

2019-03-30 21:36 UTC, Creastery requested changes

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +        return existingCodes.stream().anyMatch((existingCode) -> existingCode.equals(plannerCode));
The above code suffers from performance issues.
You can simply do:
```java
return getDegreePlannerList().stream().map(DegreePlanner::getCodes)
        .anyMatch(codes -> codes.contains(plannerCode));
```

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +    public boolean existingPlannerModules(Code plannerCode) {
Boolean methods should be named to sound like booleans.

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/model/planner/Semester.java
> +            "Semester should only contain numbers between 1 and 4. "
Since the range is small, we should define the valid range clearly:
`either 1, 2, 3 or 4`

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/model/planner/Year.java
> +            "Year should only contain numbers between 1 and 4. "
See above comment.

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +    public DegreePlanner getDegreePlanner(Year year, Semester semester) {
This creates unnecessary coupling between `DegreePlanner` with `Year` and `Semester`.
Since you are only using this method once in `PlannerAddCommand`, there is no need to extract this to an method of `AddressBook`.

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +            + PREFIX_SEMESTER + "SEMESTER\n"
Let's make it easier for users to understand how to use the application by changing:

```
planner_add year/YEAR sem/SEMESTER code/CODE [code/CODE]...
```

to:

```
planner_add code/CODE [code/CODE]... year/YEAR sem/SEMESTER 
```

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds one/multiple modules to the degree plan. "
See https://github.com/CS2113-AY1819S2-T09-1/main/pull/128#discussion_r270641397

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +            + PREFIX_SEMESTER + "2 ";
See above comment.

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    private Semester semToAdd;
You are not actually adding a new `Year` or `Semester` when trying to add module codes to a `DegreePlanner` with the corresponding `Year` and `Semester`. 

This should be named as `year` and `semester` respectively.

2019-03-30 21:36 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +     * Creates a PlannerAddCommand to add the specified {@Code code} to the degree plan.
`{@Code code}` -> `{@code code(s)}`

2019-03-31 03:29 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/model/AddressBook.java
> +    public DegreePlanner getDegreePlanner(Year year, Semester semester) {
I tried for a long time but still do not know how to get the degree planner list without having a method in Model. (once the method is in model, it also needs to be in addressbook if i'm not wrong)

To remove the coupling, I modified the implementation by reusing a method in addressbook, getDegreePlannerList. Hope it is acceptable.

2019-03-31 03:39 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    private Semester semToAdd;
I changed to yearToAddTo and semesterToAddTo to avoid repetition with the parsed arguments (also year and semester). Though they are not perfect names (a bit complicated), I believe that the names are accurate in meaning now.

2019-03-31 03:42 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    private Semester semToAdd;
and should be acceptabe?

2019-03-31 03:53 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "Some/one of the module(s) already exist in degree plan";
I was hesitating whether to use modules or module(s) in this line. As I am not sure whether module(s) is grammatically acceptable. However, modules can be inaccurate as well. Perhaps we can check again with tutors on this afterwards?

2019-03-31 10:53 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "Some/one of the module(s) already exist in degree plan";
`module(s)` is a shorthand term to signal other word endings (i.e. `module` and `modules`), and is both singular and plural. The use of such shorthand term is widely acceptable.

The problem is not the use of shorthand term, but rather, is how it is being used.

```
The new module(s) added to degree plan
```
can be rephrased to:
```
Added new module(s) to the year ... semester ... of the degree plan: ...
```

Similarly,
```
"Some/one of the module(s) already exist in degree plan"
```
can be rephrased to:
```
"The module (...) already exist in the degree plan"
```

2019-03-31 11:02 UTC, Creastery requested changes

2019-03-31 11:02 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "Some/one of the module(s) already exist in degree plan";
`module(s)` is a shorthand term to signal other word endings (i.e. `module` and `modules`), and is both singular and plural. The use of such shorthand term is widely acceptable.

The problem is not the use of shorthand term, but rather, is how it is being used.

```
The new module(s) added to degree plan
```
can be rephrased to:
```
Added new module(s) to the year ... semester ... of the degree plan: ...
```

Similarly,
```
"Some/one of the module(s) already exist in degree plan"
```
can be rephrased to:
```
"The module (...) already exist in the degree plan"
```

2019-03-31 11:02 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +            + " not exist in the module list";
See above comment.

2019-03-31 11:02 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        DegreePlanner currentDegreePlanner = model.getDegreePlannerList().stream()
`currentDegreePlanner` -> `selectedDegreePlanner`.

2019-03-31 11:02 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +    public boolean hasPlannerModule(Code plannerCode) {
Here you are trying to check if a code exists in any `DegreePlanner` within `UniqueDegreePlanner`.
This method should be named `hasPlannerCode` or even `containsCodeInPlanners` to be more precise.

2019-03-31 11:02 UTC, Creastery commented on src/main/java/seedu/address/model/ModelManager.java
> +    }
This method is unnecessary.
You should be using `getAddressBook().getDegreePlannerList()` from `PlannerAddCommand` instead.

2019-03-31 11:02 UTC, Creastery commented on src/main/java/seedu/address/model/planner/Semester.java
> +                    + "Semester should not be blank";
This can be shorten to a single line.

2019-03-31 11:02 UTC, Creastery commented on src/main/java/seedu/address/model/planner/Year.java
> +                    + "Year should not be blank";
This can be shorten to a single line.

2019-03-31 13:28 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "Some/one of the module(s) already exist in degree plan";
I mean `module(s)` is acceptable, but I do not know whether `one of the module(s)` is acceptable because `one of` should be followed by plural.

2019-03-31 13:34 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    public static final String MESSAGE_DUPLICATE_MODULE = "Some/one of the module(s) already exist in degree plan";
The correct usage of this shorthand term is:
```
One (some) of the module(s)
```

But that's besides the point. For the second message, since there can be more than one modules here, you should inform the user what module already exists in the degree plan.

So I was thinking, if you only print the first code that triggers the error, it could be:
```
The module (AA11111) already exist in the degree plan.
```

Or if you are printing all erroneous codes:
```
The module(s) (AA11111, BB2222) already exist in the degree plan
```

2019-04-01 06:57 UTC, WendyBaiYunwei commented
In addition to the requests, I also removed hasPlannerCode method to make the code more concise.

2019-04-01 08:50 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +                .collect(Collectors.toSet());
This should be declared below the first if statement.

2019-04-01 08:51 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +                .collect(Collectors.toSet());
Also, this should be renamed to `nonExistentModuleCodes`.

2019-04-01 08:56 UTC, Creastery requested changes

2019-04-01 08:56 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +     * Creates a PlannerAddCommand to add the specified {@Code code(s)} to the degree plan.
This should be `{@code codes}`

2019-04-01 08:56 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +                .collect(Collectors.toSet());
This should be renamed to `nonExistentModuleCodes`.
Also, please move this below the next if statement.

2019-04-01 09:39 UTC, Creastery requested changes
You didn't fix the unresolved issue. Please check again.

2019-04-01 10:50 UTC, WendyBaiYunwei commented
> You didn't fix the unresolved issue. Please check again.

I thought code(s) was acceptable according to https://github.com/CS2113-AY1819S2-T09-1/main/pull/109#discussion_r270642695.

I will change still.

2019-04-01 10:59 UTC, Creastery commented
> > You didn't fix the unresolved issue. Please check again.
> 
> I thought code(s) was acceptable according to [#109 (comment)](https://github.com/CS2113-AY1819S2-T09-1/main/pull/109#discussion_r270642695).
> 
> I will change still.

That comment was to let you know that you should be using `@code`.

2019-04-01 12:15 UTC, Creastery approved these changes

2019-04-01 12:15 UTC, lycjackie approved these changes

2019-04-01 12:15 UTC, Letm3through approved these changes

2019-04-01 12:18 UTC, merged