Bug fix for command 'requirement_add'
CS2113-AY1819S2-T09-1/main pull request #112
Opened 2019-03-21 19:05 UTC by chyeo

The current implementation of the 'requirement_add' command has a bug where no more than 1 module code can be added to a requirement category. 

The bug was caused by not using a new Set<Code> variable, in the logic flow when a module code is added to a requirement category. The fix was to add both existing and current module code to the new variable and pass in the new variable when adding a module code.

The logic of 'RequirementAddCommandParser' was updated as well so that the class will not create a new RequirementCategory object and instead only pass data that was parsed. In this case, only the Name and Set<Code> will be passed to 'RequirementAddCommand' class.

Relevant test cases were also updated to ensure the desired behavior for the 'requirement_add' command was achieved.

2019-03-22 18:55 UTC, Creastery requested changes

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +    public boolean hasModuleCodeAdded(RequirementCategory currentRequirementCategory,
Rename `hasModuleCodeAdded` -> `hasModuleCode`

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +        Set<Code> currentList = currentRequirementCategory.getCodeList();
Let's avoid using `xyzList` when we are actually trying to work with `Set` instead of `List`.
Please refactor:
* `currentList` -> `currentSet`
* `RequirementCategory#getCodeList()` -> `RequirementCategory#getCodeSet()`

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +                if (existingCode.value.equals(newCode.value)) {
You should not be checking the raw `value` directly!
Instead, `Code#equals()` should be used here.

Anyway, this nested for loop can be simplified using `.stream().anyMatch(...)`.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +    public Set<Code> newCodeSet(Set<Code> currentCodeSet, Set<Code> inputCodeSet) {
Having a `newCodeSet(...)` method in `RequirementCategory` makes no sense at all, as `RequirementCategory` is not an object builder utility class!

Given the simplicity of this method's objectives, I think this method can be removed completely.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +    public Integer getNewCreditsAmount(ObservableList<Module> moduleList, Set<Code> codeSet) {
This method is implemented as an extension to your feature, and does not contribute in fixing the bug mentioned.
Please avoid mixing features within PRs, as this makes reviewing extremely.
Having said that, please remove this method from this PR. Thank you.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
>       * Returns true if the list contains an equivalent requirement as the given argument.
Can you update the JavaDoc for `contains(...)`? 
The argument is not a `RequirementCategory `, but instead, it is a `Name`.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +    public boolean contains(Name toCheck) {
I see value in keeping the original implementation of the `contains(...)` method.

Let's keep both the original implementation and your amended implementation of `contains(...)`.
(i.e. overloading `contains(...)` method)

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +    public RequirementCategory getRequirementCategoryName(Name toCheck) {
`getRequirementCategoryName` can mean that you want to get the `Name` of a `RequirementCategory`.
Please rename `getRequirementCategoryName(...)` to `getRequirementCategory`.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +        if (contains(toAdd.getName())) {
Revert this changes in view of above comments.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +    public void addModuleToRequirementCategory(RequirementCategory currentRequirementCategory,
This method is completely redundant. `setRequirementCategory` already does exactly what this method does!

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +    @Override public Iterator<RequirementCategory> iterator() {
Avoid unnecessary changes.
Let's separate `@Override` annotations and method declarations with a new line.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +    @Override public boolean equals(Object other) {
Avoid unnecessary changes.
Let's separate `@Override` annotations and method declarations with a new line.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +    @Override public int hashCode() {
Avoid unnecessary changes.
Let's separate `@Override` annotations and method declarations with a new line.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +            if (toCheck.equals(internalList.get(i).getName())) {
Think you can simplify the loop using streams and filter.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +    public RequirementCategory getRequirementCategoryName(Name requirementCategoryName) {
Please rename `getRequirementCategoryName(...)` -> `getRequirementCategory(...)`

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +    public void addModuleToRequirementCategory(RequirementCategory currentRequirementCategory,
As mentioned previously, this method is redundant, and hence should be removed.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/Model.java
> +    RequirementCategory getRequirementCategoryName(Name requirementCategoryName);
Please rename `getRequirementCategoryName(...)` -> `getRequirementCategory(...)`

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/model/Model.java
> +    void addModuleToRequirementCategory(RequirementCategory currentRequirementCategory,
Please remove this redundant method (as discussed above).

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> +            "The module does not exists in the module list";
You need to explain the _why_ more.

Example:
"The module **to be added to the requirement category** does not exists in the module list!"

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> +    private final Set<Code> codeSet = new HashSet<>();
To be consistent with the rest of the `XYZCommand` classes, you should name this variable as `toAdd`.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> +    private final Name requirementCategoryName;
To be consistent with the rest of the `XYZCommand` classes, you should name this variable as `tofind`.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
>      public static final String MESSAGE_REQUIREMENT_CATEGORY_DOES_NOT_EXIST =
`MESSAGE_REQUIREMENT_CATEGORY_DOES_NOT_EXIST` -> `MESSAGE_NONEXISTENT_REQUIREMENT_CATEGORY`.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> +        Set<Code> newCodeSet = currentRequirementCategory.newCodeSet(currentRequirementCategory.getCodeList(), codeSet);
Should be:
```java
Set<Code> newCodeSet = new Set<>(currentRequirementCategory.getCodeSet());
newCodeSet.addAll(toAdd);
```

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> +                requirementCategoryName, newCredit, newCodeSet);
This seems to imply that `Credits` of `RequirementCategory` is the "current progress".
But, in actual fact, it is the number of modular credits required to satisfy the requirement set out in this `RequirementCategory`!

If you want to track the current `Credits`, you should be modifying the model for `RequirementCategory` to add a new attribute.

2019-03-22 18:55 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> -                && toAdd.equals(((RequirementAddCommand) other).toAdd));
Why is the `equals(...)` method removed?

2019-03-22 18:55 UTC, Creastery commented on src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java
> +    public RequirementCategoryBuilder withCodes(String ... codes) {
Any particular reason for this change in method signature?
By the way, please remove the space before `...`

2019-03-23 06:45 UTC, chyeo commented on src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java
> +    public RequirementCategoryBuilder withCodes(String ... codes) {
This is to match the `public static Set<Code> getCodeSet(String... strings)` method in `SampleDataUtil.java`

2019-03-24 08:47 UTC, Creastery requested changes

2019-03-24 08:47 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +                && contains(editedRequirementCategory)) {
There is no need to put the conditions on two lines when it can fit within a single line!

2019-03-24 08:47 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +            .collect(Collectors.toCollection(ArrayList:: new));
Collecting the results to an `ArrayList` just to return the first filtered value (if present) is an overkill.
You could have simply simply returned:
```java
internalList.stream()
        .filter(requirementCategory -> requirementCategory.getNames().equals(toCheck))
        .findFirst()
        .orElse(null);
```

2019-03-24 08:47 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +    public boolean hasModuleCode(RequirementCategory currentRequirementCategory, Set<Code> toCheck) {
Why do you need to pass `RequirementCategory ` as an argument to this method? 
This method is an instance method!

2019-03-24 08:47 UTC, Creastery commented on src/main/java/seedu/address/storage/JsonSerializableRequirementCategoryList.java
> +            if (requirementCategoryList.hasRequirementCategory(requirementCategory.getName())) {
Why lookup the object in the list by name when you already have the object reference?

2019-03-24 08:47 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java
> +    @Test public void execute_requirementCategoryDoesNotExist_throwsCommandException() {
Can we standardise the naming to match `MESSAGE_NONEXISTENT_REQUIREMENT_CATEGORY` please?

2019-03-24 08:47 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java
> +        Name requirementCategoryName = new Name("DOES NOT EXIST");
See above comment.

2019-03-24 08:47 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java
> +    @Test public void execute_moduleCodeToBeAddedDoesNotExist_throwsCommandException() {
See above comment.

2019-03-24 08:47 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java
> +    @Test public void execute_moduleCodeToBeAddedAlreadyExistInRequirementCategory_throwsCommandException() {
Can we standardise the naming to match `MESSAGE_DUPLICATE_CODE` please?

2019-03-24 08:47 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> +            }
This loop can be simplified to an if statement as such:
```java
if (toAdd.stream().anyMatch(code -> model.hasModuleCode(code) == false)) {
    throw new CommandException(MESSAGE_NONEXISTENT_CODE);
}
```

2019-03-25 04:51 UTC, Creastery requested changes

2019-03-25 04:51 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> +        if (isNull(currentRequirementCategory)) {
This should have been `currentRequirementCategory == null`.
Don't abuse `Objects.isNull`!
The documentation at [Objects.isNull](https://docs.oracle.com/javase/9/docs/api/java/util/Objects.html#isNull-java.lang.Object-) mentions the API note:
```
This method exists to be used as a Predicate, filter(Objects::isNull)
```

2019-03-25 04:51 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +        return (getCodeSet().stream().anyMatch((current) -> getCodeSet().containsAll(toCheck)));
This is incorrect.
What you are trying to do is to determine if any `Code` in `toCheck` is already present in `codeSet`.
But instead, what's done here was:
For all elements of `getCodeSet()`, check if `getCodeSet()` contains all elements of `toCheck`

This should be:
```java
public boolean hasModuleCode(Set<Code> codeSetToCheck) {
    return codeSetToCheck.stream().anyMatch(codeToCheck -> codeSet.contains(codeToCheck));
}
```

Please update the comments to reflect this accordingly as well.

2019-03-25 04:51 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/RequirementCategory.java
> +        return (getCodeSet().stream().anyMatch((current) -> getCodeSet().containsAll(toCheck)));
Few things you should note as well:
1. Avoid name like `current` (too vague; not descriptive enough)
2. Avoid using getter methods (i.e. `getCodeSet()`) within the class (you have access to private class attributes!)
3. Let's stick to no parenthesis for single parameter for lambda expressions (i.e. remove `()` around `codeToCheck`)

2019-03-25 14:51 UTC, Creastery requested changes

2019-03-25 14:51 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
> -                && toAdd.equals(((RequirementAddCommand) other).toAdd));
You need to keep this deleted line too!

2019-03-25 14:51 UTC, Creastery commented on src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
> +        return internalList.stream().anyMatch(toCheck::equals);
Please keep the original `toCheck::isSameRequirementCategory`.
The `equals()` checks are a lot stricter.

2019-03-25 15:16 UTC, Creastery approved these changes

2019-03-25 15:24 UTC, merged