UI: update on degree planner
CS2113-AY1819S2-T09-1/main pull request #114
Opened 2019-03-23 15:11 UTC by truegitnovice

Currently, `DegreePlannerListPanel` directly creates `DegreePlannerCard` on `FlowPane` which makes the real-time updates of contents in degree planners difficult. 

Hence, for simplicity, let's convert current implementation of `FlowPane` to `ListView`.
In addition, let's add some CSS styles for degree planner related UI so that it is easier to update them in future.

2019-03-24 12:07 UTC, Creastery requested changes

2019-03-24 12:07 UTC, Creastery commented on src/main/java/seedu/address/ui/DegreePlannerCard.java
> +            setStyle("-fx-font-size: 15px;");
Instead of setting a style here, could we set a class to the cell instead and add the necessary CSS styling for the class?

2019-03-24 12:07 UTC, Creastery commented on src/main/resources/view/DarkTheme.css
> +    -fx-font-size: 18px;
There seems to be an overlap between this CSS styling and the one above (`-fx-font-size: 15px;`).
Can you explain the differences please?

2019-03-24 12:28 UTC, truegitnovice commented on src/main/resources/view/DarkTheme.css
> +    -fx-font-size: 18px;
There are two `ListView`s in the `DegreePlanner`. One is inside the `PlannerPanel`.

2019-03-24 12:29 UTC, truegitnovice commented on src/main/java/seedu/address/ui/DegreePlannerCard.java
> +            setStyle("-fx-font-size: 15px;");
I have moved all the CSS stylings to the stylesheet as you suggested. Thank you.

2019-03-25 05:19 UTC, Creastery approved these changes

2019-03-25 05:19 UTC, Creastery commented
LGTM. Approving and merging.
Thanks for updating the UI accordingly!

2019-03-25 05:23 UTC, merged

2019-03-25 05:27 UTC, truegitnovice commented
Thank you for the great review!