Logic: improve `FindCommand` to take in boolean expression
CS2113-AY1819S2-T09-1/main pull request #119
Opened 2019-03-25 14:13 UTC by lycjackie

Our implementation for `FindCommandParser#getKeywordsPredicate` result
an implicit boolean OR predicate.

This is not desirable for our users as they will not be able to have tighter 
search results e.g. Finding for module's `name` with both
`Programming` and `Methodology`.

With the aim to improve our `FindCommand`

The following steps are made in order for our `FindCommand` to take in a
boolean expression.

1. Create our `BooleanExpressionParser` which handle all the parsing
2. Create our `Operator` class which handle what are the operators we
need.
3. Refactor our current `FindCommandParser` to utilise the 
`BooleanExpressionParser#parse`

2019-03-27 06:09 UTC, Creastery requested changes
Good job implementing Shunting-yard algorithm while utilising OOP concepts as well!
Just a quick remark - 
I noticed you added support for handling parenthesis. 
Could you include that in the find command usage examples as well? 
I understand that due to the way how `ArgumentMultimap` tokenizes the input by spaces, all operators and keywords need to be delimited by whitespace. 
Nevertheless, since you already handle parenthesis, we should include examples of proper usage, and try to tokenize the input better in the next iteration.

Thanks for the effort!

2019-03-27 06:25 UTC, lycjackie commented
> Good job implementing Shunting-yard algorithm while utilising OOP concepts as well!
> Just a quick remark -
> I noticed you added support for handling parenthesis.
> Could you include that in the find command usage examples as well?
> I understand that due to the way how `ArgumentMultimap` tokenizes the input by spaces, all operators and keywords need to be delimited by whitespace.
> Nevertheless, since you already handle parenthesis, we should include examples of proper usage, and try to tokenize the input better in the next iteration.
> 
> Thanks for the effort!

Alright! 

Although there are some basic handling of the parenthesis, I believe it is not ready for proper usage. 

I will open an issue on this and will refine it further before updating the examples.

Many thanks for the reviews!

2019-03-27 08:03 UTC, Creastery commented
> Although there are some basic handling of the parenthesis, I believe it is not ready for proper usage.
> 
> I will open an issue on this and will refine it further before updating the examples.
Sure, I agree that the an issue can be created so that we have in sight of this potential enhancement that can be done in v1.4.
However, we still need to update the usage to showcase some potential usage, and also specify the constraints better so that users are not confused.

2019-03-27 13:25 UTC, lycjackie commented
> > Although there are some basic handling of the parenthesis, I believe it is not ready for proper usage.
> > I will open an issue on this and will refine it further before updating the examples.
> 
> Sure, I agree that the an issue can be created so that we have in sight of this potential enhancement that can be done in v1.4.
> However, we still need to update the usage to showcase some potential use cases, and also specify the constraints better so that users are not confused.

I have updated the command usage for `FindCommand`. 

As for the constraints would it better to indicate them in our `UserGuide`?

2019-03-29 14:32 UTC, Creastery commented
> 
> I have updated the command usage for `FindCommand`.
> 
> As for the constraints would it better to indicate them in our `UserGuide`?

I think the current constraints you have included now are okay. We can refine this further in v1.4 to make it more user-friendly.

As discussed, there was a need to create a custom tokenizer (`BooleanExpressionTokenizer`) despite already having `ArgumentTokenizer` and `StringTokenizer` to reduce unnecessary and additional overhead in parsing and processing the arguments and operators as tokens in `BooleanExpressionParser`. I hope the `BooleanExpressionTokenizer` class I wrote is robust enough for your needs. 
Let me know if you need any advice extending its functionality further.

Besides that, the necessary changes to the `Name` class (in PR #135) is already merged, so I don't suppose there is any further issues preventing parsing of operators (i.e. `(`, `)`, `&`, `|`) by `BooleanExpressionParser` properly. I'll stress test the `find` command a bit more before approving.

2019-03-29 14:38 UTC, lycjackie commented
> > I have updated the command usage for `FindCommand`.
> > As for the constraints would it better to indicate them in our `UserGuide`?
> 
> I think the current constraints you have included now are okay. We can refine this further in v1.4 to make it more user-friendly.
> 
> As discussed, there was a need to create a custom tokenizer (`BooleanExpressionTokenizer`) despite already having `ArgumentTokenizer` and `StringTokenizer` to reduce unnecessary and additional overhead in parsing and processing the arguments and operators as tokens in `BooleanExpressionParser`. I hope the `BooleanExpressionTokenizer` class I wrote is robust enough for your needs.
> Let me know if you need any advice extending its functionality further.
> 
> Besides that, the necessary changes to the `Name` class (in PR #135) is already merged, so I don't suppose there is any further issues preventing parsing of operators (i.e. `(`, `)`, `&`, `|`) by `BooleanExpressionParser` properly. I'll stress test the `find` command a bit more before approving.

Many thanks for your `BooleanExpressionTokenizer`, it was very easy to use and 
the implementation is quite similar to `StringTokenizer` 👍 

I suppose this also resolves #129, where explicit whitespaces is needed to separate operators

2019-03-29 14:54 UTC, Creastery requested changes

2019-03-29 14:54 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all modules which satisfies the expression"
Perhaps it would be better to phrase this as:
"find: Finds all modules which satisfy the expression of search conditions specified and displays them as a list with index numbers."

2019-03-29 14:54 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Note: you can also use parenthesis to indicate which expression to evaluate first.\n"
Perhaps consider rephrasing the above two lines as such:
```
You can chain different search condition together using operators:
OPERATOR "&&" for logical "AND" operation (both conditions A AND B must match)
OPERATOR "||" for logical "OR" operation (either conditions A OR B must match)
You can also use parenthesis to group what search conditions to evaluate first.
```

2019-03-29 14:56 UTC, Creastery commented
> Many thanks for your `BooleanExpressionTokenizer`, it was very easy to use and
> the implementation is quite similar to `StringTokenizer` 👍

No problem! Good to hear that it works well :)

> I suppose this also resolves #129, where explicit whitespaces is needed to separate operators

Yes, merging this PR will also resolve and fix #129.

2019-03-30 03:35 UTC, Creastery approved these changes
LGTM. Approving and merging.
Thanks for making the necessary changes and implementing additional unit tests to ensure that the functionality of the feature works as intended.

2019-03-30 03:48 UTC, merged