developer guide: amend planner_add and planner_delete
CS2113-AY1819S2-T09-1/main pull request #127
Opened 2019-03-27 07:08 UTC by WendyBaiYunwei

2019-03-27 07:36 UTC, Letm3through requested changes

2019-03-27 07:36 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +|`* * *` |user |remove modules from my degree planner |ensure that the modules in my degree planner are the right ones
Perhaps consider changing `ensure that the modules in my degree planner are the right ones` to `remove modules that I am not interested in taking from my degree planner`?

2019-03-27 07:36 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +By: `Team T09-1`      Since: `Feb 2019`      Licence: `MIT`
May I know the point of this?
Please ensure that there isn't any changes made here unless there is a valid reason for this.

2019-03-27 07:36 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +** 1b1. Application shows an error message that modules specified by user already exists in degree planner.
I believe `exist` here is referring to the modules. If so, please change `exist` to `exists`.

2019-03-27 07:36 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +* 1b. The modules already exist in the degree planner.
Based on the current `planner_add` that you are working on the PR, if one of the modules entered already exist and other modules are new to the degree planner, it will just display the message stating that `This module already exists in the degree planner`. Hence, you may want to consider making this statement clear.

2019-03-27 08:35 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +By: `Team T09-1`      Since: `Feb 2019`      Licence: `MIT`
I did not modify this. do not know what happened. but they are exactly the same

2019-03-27 08:49 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +By: `Team T09-1`      Since: `Feb 2019`      Licence: `MIT`
i cannot resume also

2019-03-30 00:27 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +|`* * *` |user |remove modules from my degree planner |remove modules that I am not interested in taking
i didn't modify modules to one/multiple modules here to maintain consistency among the stories and user stories don't need to be so specific

2019-03-31 02:14 UTC, Letm3through requested changes
Please mark as resolve when you have made the changes accordingly so the reviewers can see what have been reviewed.
Please also take note of https://github.com/CS2113-AY1819S2-T09-1/main/pull/128#discussion_r270511056 and change accordingly.
Also, for one/multiple modules, I think it would be better to simply say module(s).
Thank you.

2019-03-31 02:14 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +=== Use case: Delete one/multiple modules from degree plan
Please changes to rest of `Delete` to `Remove` as we have discussed in https://github.com/CS2113-AY1819S2-T09-1/main/pull/128#discussion_r270511056 other than just user stories to not make any confusion to readers.

2019-03-31 13:42 UTC, Letm3through requested changes
There are few more changes that could be made to improve on the developer guide. Please make following changes. Thank you. 

In addition, I realised that in this PR, coveralls which is supposed to be not affected is indicating a drop. I realised your branches are all far behind the upstream. I am not too sure but perhaps, this is the problem. Hence, I suggest you may want to try fixing it by updating your branch to keep up to date with the upstream.

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +from my degree plan
I think you can just say `remove modules that I am not interested in taking` since you mentioned degree plan in `remove modules from my degree plan`

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +* 1b. Any of the module(s) already exists in the degree plan.
Since you said `module(s)`, I think it is better to write `The module(s)`...

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +** 1b1. Application shows an error message that one/some of the module(s) specified by user already exist in degree plan.
I suggest just saying `module(s)` to be consistent instead of `one/some of the module(s)`

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +* 1c. Any of the module(s) does not exist in the module list.
Same thing mentioned above: `The module(s)`

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +** 1c1. Application shows an error message that one/some of the module(s) specified by user do not exist in the module list.
Refer to previous comments

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +* 3b. Any of the module(s) does not exist in the degree plan.
Refer to previous comments

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +** 3b1. Application shows an error message that one/some of the module(s) specified by user do not exist in degree plan.
Refer to previous comments

2019-03-31 13:42 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +By: `Team T09-1`      Since: `Feb 2019`      Licence: `MIT`
One way to try fixing this is, perhaps try copy paste this parts from the upstream master.

2019-04-01 05:16 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +* 1b. Any of the module(s) already exists in the degree plan.
If I use `module(s)` only, it is hard to show that when any of the `modules` exists, the command will not work.
For instance, if I add in code CS1010 and CS1231, and CS1010 does not exist while CS1231 exists, then the addition will still be rejected.
Therefore I feel `Any of` is necessary to make this clear.

2019-04-01 05:18 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +** 1b1. Application shows an error message that one/some of the module(s) specified by user already exist in degree plan.
similar to the comment above, not all the module(s) the user inputs may exist in degree plan.  Some of them may be valid modules still.

2019-04-01 05:19 UTC, WendyBaiYunwei commented
> There are few more changes that could be made to improve on the developer guide. Please make following changes. Thank you.
> 
> In addition, I realised that in this PR, coveralls which is supposed to be not affected is indicating a drop. I realised your branches are all far behind the upstream. I am not too sure but perhaps, this is the problem. Hence, I suggest you may want to try fixing it by updating your branch to keep up to date with the upstream.

Sorry, indeed I have not been updating this branch.

2019-04-01 05:36 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +** 1b1. Application shows an error message that one/some of the module(s) specified by user already exist in degree plan.
I think `module(s)` itself implies that
> not all the module(s) the user inputs may exist in degree plan. Some of them may be valid modules still.

2019-04-01 05:45 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +* 1b. Any of the module(s) already exists in the degree plan.
I think `The module(s)` itself already implying the message since it means that one of the module or more exist(s). 
However, if you feel that there is need to better phrase this part to give clearer meaning to the users, it's more than welcome to do so perhaps by better phrasing the sentence.
May I know is there any particular reason why you use `Any of the module(s)` instead of `Any of the modules`?

2019-04-01 07:26 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +* 1b. Any of the module(s) already exists in the degree plan.
By using "the module(s)", we are referring to the module(s) added, because the "module(s) added" is the only term mentioned previously. I do not think it can refer to only the module(s) that already exist, which was never mentioned previously. I will think about how to rephrase this part better. Meanwhile, please give me some suggestions if you think of any. Thank you.

2019-04-01 08:35 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +* 1b. Any of the module(s) already exists in the degree plan.
I rephrased the part to (Any of) the module(s).

2019-04-01 08:37 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +** 1b1. Application shows an error message that one/some of the module(s) specified by user already exist in degree plan.
I really think that `module(s)` itself only means the modules added, according to the context

2019-04-01 08:39 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +* 1b. Any of the module(s) already exists in the degree plan.
> By using "the module(s)", we are referring to the module(s) added, because the "module(s) added" is the only term mentioned previously. I do not think it can refer to only the module(s) that already exist, which was never mentioned previously. 

In fact, we are referring to `the module(s)`... I think `Any of` here is really redundant.

2019-04-01 12:59 UTC, Letm3through requested changes
There are still some changes that you might want to consider. Please take a look at the comments.

2019-04-01 12:59 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +** 3b1. Application shows an error message that the module(s) specified by user does not exist in degree plan.
You may want to add  `the`: `does not exist in the degree plan`.

2019-04-01 12:59 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +*** 1c1a. In cases where step 1b takes place simultaneously with step 1c, step 1c1 will not take place.
Is this necessary? I think by stating 1a, 1b ..., the order of logical checks are clear.

2019-04-01 13:09 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +** 3b1. Application shows an error message that the module(s) specified by user does not exist in degree plan.
Sorry I do not really understand what you mean. Could you clarify a bit?

2019-04-01 15:41 UTC, Letm3through approved these changes

2019-04-01 15:42 UTC, merged