user guide: amend details about planner_add and delete
CS2113-AY1819S2-T09-1/main pull request #128
Opened 2019-03-27 07:17 UTC by WendyBaiYunwei

2019-03-27 08:33 UTC, Creastery requested changes

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +* Items with `…` after them are parameters that can be used multiple times (including zero times)
Why is there unnecessary changes here?

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +Format: `planner_add code/CODE [code/CODE]… year/YEAR sem/SEMESTER`
Your examples below don't match the same format you specified here.
Which is correct?

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds module CS1010 to year 3 semester 2.
See above comment.

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds modules CS1231 and CS2040C to year 1 semester 2.
See above comment.

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +Format: `planner_delete code/CODE [code/CODE]…`
Likewise, your examples below don't match the same format you specified here.
Which is correct?

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +* `planner_delete CS1231` +
See above comment.

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +Deletes modules CS2100 and CS2040C from the degree planner.
See above comment.

2019-03-27 08:33 UTC, Creastery commented on docs/UserGuide.adoc
> +e.g.  `planner_delete CS1231 CS1010`
See above comments.

2019-03-27 08:56 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +* Items with `…` after them are parameters that can be used multiple times (including zero times)
I am not sure. I did not deliberately change here. but they are the same. i cannot resume the change

2019-03-27 09:40 UTC, Creastery commented on docs/UserGuide.adoc
> +* `YEAR` and `SEMESTER` must be either 1 or 2.
Why?

2019-03-27 09:49 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +* `YEAR` and `SEMESTER` must be either 1 or 2.
I thought special semesters were not supported any more. Will amend

2019-03-27 11:24 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +* `YEAR` and `SEMESTER` must be either 1 or 2.
I think special sem hasn't been implemented yet. Can we indicate special sem after it's implemented?

2019-03-28 09:30 UTC, Creastery commented on docs/UserGuide.adoc
> +* `YEAR` and `SEMESTER` must be either 1 or 2.
> I think special sem hasn't been implemented yet. Can we indicate special sem after it's implemented?

We already implemented special term semesters in the form of Semester 3 and 4 respectively in PR #34. 

I don't see reason to drop support for special term semesters. In fact, by removing special term semesters, we are reducing the scope of our target audience further, which is already well-defined at the moment.

2019-03-28 09:43 UTC, Creastery commented
Can we standardise the content further?

Let's rephrase:
```
Adds module CS1010 to year 3 semester 2.
```

to
```
Adds module code CS1010 to year 3 semester 2 of the degree plan.
```

2019-03-28 23:06 UTC, WendyBaiYunwei commented
> Can we standardise the content further? An example is given below.
> 
> Let's rephrase:
> 
> ```
> Adds module CS1010 to year 3 semester 2.
> ```
> to
> 
> ```
> Adds module code CS1010 to year 3 semester 2 of the degree plan.
> ```

Just to confirm. it should be degree planner instead of degree plan right?

2019-03-29 17:29 UTC, Creastery commented
> > Can we standardise the content further? An example is given below.
> > Let's rephrase:
> > ```
> > Adds module CS1010 to year 3 semester 2.
> > ```
> > to
> > ```
> > Adds module code CS1010 to year 3 semester 2 of the degree plan.
> > ```
> 
> Just to confirm. it should be degree planner instead of degree plan right?

No, that's not what I meant.

What I meant was that we should avoid using `degree planner` interchangeably with `degree plan`.
`Degree plan` here refers to the `plan`, whereas `degree planner` can mean the application (the whole application can be seen as a `degree planner`, a tool to help users `plan` their degree).

2019-03-29 17:40 UTC, Creastery requested changes
Please also see https://github.com/CS2113-AY1819S2-T09-1/main/pull/128#issuecomment-478083913 and make the necessary changes.

2019-03-29 17:40 UTC, Creastery commented on docs/UserGuide.adoc
> +* All the modules to add must exist in the application.
`application` -> `module list`.

2019-03-29 17:40 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds module code CS2113T, CS2040C and CS2107 to year 3 special semester 1 of the degree planner.
`year 3 special semester 1` -> `year 3 special term semester 1`

2019-03-29 17:40 UTC, Creastery commented on docs/UserGuide.adoc
> +Deletes a set of existing modules from the degree planner. +
A set of existing modules won't really make sense if the user is just trying to remove a module code from the degree plan.

Besides that, you should be consistent in the phrasing with `planner_add` here.
`Removes existing modules from the degree planner.` would probably be a lot better.

I think `planner_delete` should also be renamed to `planner_remove` to avoid confusion as to what this command does, as `planner_delete` can imply removing the entire module from the entire `degree planner` (which can be treated as the entire application) instead of simply removing the module from the `degree plan`.

@truegitnovice Since you are working on the degree planner functionalities as well, may I know what's your take on this?

2019-03-29 17:40 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds module code CS2113T, CS2040C and CS2107 to year 3 special semester 1 of the degree planner.
Also, can you also decide if you want to use `module code` or `module` throughout for consistency?

2019-03-29 18:14 UTC, truegitnovice commented on docs/UserGuide.adoc
> +Deletes a set of existing modules from the degree planner. +
@Creastery @WendyBaiYunwei 
Since `planner_delete`  is not deleting a degree plan or removing the entire modules from the entire degree plan and it is just removing the module codes from the degree plan, I think it can be misleading to the user. We want to give a clear idea what the command does to the user. Hence, I agree with the **Creastery** and find it necessary on renaming `planner_delete` to `planner_remove` in order to not to confuse the users.

2019-03-30 00:22 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +Deletes one/multiple existing modules from the degree plan. +
I didn't change the delete to remove in the elaboration because deleting modules still use the word "delete"

2019-03-30 21:06 UTC, Creastery requested changes

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Adding one/multiple modules to degree plan : `planner_add` `[coming in v2.0]`
I think you can simplify `one/multiple modules` to `module(s)`.
As discussed last week, we want to standardise section headers by keeping it as concise as possible.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds one/multiple existing modules to the degree plan. +
Please replace `one/multiple modules` with `module(s)`.
Also, including `existing` here is repetitive of the point you are going to mention below, so I think you can remove it here to keep the description concise.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +* All the module/modules to add must exist in the module list.
Please replace `one/multiple modules` with `module(s)`.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds module CS1010 to year 1 special term semester 1 of the degree plan.
Sorry, I wasn't specific enough in my previous example of how to rephrase this.
What I meant was to replace `year 1 semester 3` with `year 3 semester 3 (special term semester 1)`.
We have to highlight to the users what semester it should be when entering within the application, but we also need to link back to what `semester 3` is in reality.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds modules CS1231 and CS2040C to year 1 special term semester 2 of the degree plan.
See above comment.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Deleting one/multiple modules from degree plan : `planner_remove` `[coming in v2.0]`
See below comment.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +* After deleting, the changes will be reflected in the degree plan accordingly.
See above comment.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +Deletes modules CS2100 and CS2040C from the degree plan.
See above comment.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +* *Delete one/multiple modules from degree plan* : `planner_remove code/CODE [code/CODE]…` +
See above comments.

2019-03-30 21:06 UTC, Creastery commented on docs/UserGuide.adoc
> +Deletes one/multiple existing modules from the degree plan. +
I don't get what you are trying to say.
I think we should use `remove` instead of `delete`.

Previously, I mentioned that:

> I think `planner_delete` should also be renamed to `planner_remove` to avoid confusion as to what this command does, as `planner_delete` can imply removing the entire module from the entire `degree planner` (which can be treated as the entire application) instead of simply removing the module from the `degree plan`.

Besides that, `removing` modules instead of `deleting` modules sounds more sensible when one amends their degree plan.

One `adds` a module to their degree plan, then `removes` a module from their degree plan.
v.s.
One `adds` a module to their degree plan, then `deletes` a module from their degree plan.

2019-03-31 04:46 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Adding module code(s) to degree plan : `planner_add` `[coming in v2.0]`
I changed module to module code to match requirement_add. Also, I feel that module code may be more accurate. Yet, I'm not sure whether it is necessary. Please just let me know if you need me to change it back.

2019-03-31 05:06 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Adding module code(s) to degree plan : `planner_add` `[coming in v2.0]`
I decided to change back because `module` is more concise.

2019-03-31 10:35 UTC, Creastery requested changes

2019-03-31 10:35 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds module CS1231 and CS2040C to year 1 semester 4 (special term semester 2) of the degree plan.
`module` -> `modules`

2019-03-31 10:35 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds module CS2113T and CS2107 to year 1 semester 2 of the degree plan.
See above comment.

2019-03-31 10:35 UTC, Creastery commented on docs/UserGuide.adoc
> +Removes module CS2100 and CS2040C from the degree plan.
See above comment.

2019-03-31 14:52 UTC, Creastery requested changes
Please see minor changes to be made.

2019-03-31 14:52 UTC, Creastery commented on docs/UserGuide.adoc
> +* All the module(s) to add must exist in the module list.
`to add` -> `to be added`

2019-03-31 14:52 UTC, Creastery commented on docs/UserGuide.adoc
> +* After adding, the changes will be reflected in the degree plan accordingly.
Rephrase to:
```
After adding, the updated degree plan will be displayed.
```

2019-03-31 14:52 UTC, Creastery commented on docs/UserGuide.adoc
> +* After removing, the changes will be reflected in the degree plan accordingly.
See above comment.

2019-04-01 09:02 UTC, Creastery requested changes

2019-04-01 09:02 UTC, Creastery commented on docs/UserGuide.adoc
> +** 3 or 4 for `SEMESTER` indicates special term semesters 1 and 2 respectively.
This should be `3 and 4` instead of `3 or 4`.

2019-04-01 09:02 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Adding module(s) to degree plan : `planner_add` `[coming in v2.0]`
`Adding` -> `Add` to be consistent with command summary.

2019-04-01 09:02 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Removing module(s) from degree plan : `planner_remove` `[coming in v2.0]`
`Removing` -> `Remove` to be consistent with command summary.

2019-04-01 09:29 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Adding module(s) to degree plan : `planner_add` `[coming in v2.0]`
The titles and command summary have different format. "Adding" is consistent with the rest of the commands

2019-04-01 11:13 UTC, Letm3through requested changes
Please solve merge conflict before the reviews

2019-04-01 12:23 UTC, Creastery requested changes

2019-04-01 12:23 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Adding module(s) to degree plan : `planner_add` `[coming in v2.0]`
Please remove `[coming in v2.0]`.

2019-04-01 15:35 UTC, Letm3through approved these changes

2019-04-01 15:35 UTC, Creastery approved these changes

2019-04-01 15:37 UTC, merged