RequirementCategory: implement `requirement_list` command
CS2113-AY1819S2-T09-1/main pull request #133
Opened 2019-03-29 07:36 UTC by chyeo

resolves issue #132

The current implementation of the application does not allow users to be able to list all the requirement categories in the application.

Let's create a command to allows users to be able to view all the requirement categories
and update the UI to display all the requirement categories as well

2019-03-30 17:19 UTC, Creastery commented
Sorry, I haven't had time to review your PR.
Anyhow, @lycjackie can you help to take a look to ensure that the Logic component makes sense for the this implementation?

2019-03-30 20:22 UTC, lycjackie requested changes

2019-03-30 20:22 UTC, lycjackie commented on src/main/java/seedu/address/logic/commands/RequirementListCommand.java
> +                    .map(Integer::parseInt).reduce(0, (left, right) -> left + right);
Although I know this is doing a sum. 
You might want to consider renaming the left, right variable

2019-03-30 20:22 UTC, lycjackie commented
I will take a look again when I'm free again. Kind of late...

2019-03-30 22:40 UTC, Creastery requested changes

2019-03-30 22:40 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +    public Module hasModule(Code code) {
This shouldn't sound like a boolean.

2019-03-30 22:40 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementListCommand.java
> +            requirementListContent.append(requirementCategory.getName() + " \n");
Please use StringBuilder correctly:
```java
requirementListContent.append(requirementCategory.getName()).append(" \n");
```

2019-03-30 22:40 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementListCommand.java
> +            requirementListContent.append("Credits: " + credits + "/" + requirementCategory.getCredits() + " \n");
Please use StringBuilder correctly:
```java
requirementListContent.append("Credits: ").append(credits).append('/')
        .append(requirementCategory.getCredits()).append(" \n");
```

2019-03-30 22:40 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/RequirementListCommand.java
> +                        .map(Code::toString).sorted().collect(Collectors.joining(", ")));
Please use StringBuilder correctly:
```java
requirementListContent.append("Modules: ").append(requirementCategory.getCodeSet().stream()
        .map(Code::toString).sorted().collect(Collectors.joining(", ")));
```

2019-03-30 22:40 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementListCommandTest.java
> +            requirementListContent.append(requirementCategory.getName() + " \n");
Fix `StringBuilder` usage here.

2019-03-30 22:40 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementListCommandTest.java
> +            requirementListContent.append("Credits: " + credits + "/" + requirementCategory.getCredits() + " \n");
Fix `StringBuilder` usage here.

2019-03-30 22:40 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementListCommandTest.java
> +                requirementListContent.append("Modules: " + requirementCategory.getCodeSet().stream()
Fix `StringBuilder` usage here.

2019-03-30 22:40 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RequirementListCommandTest.java
> +
Avoid unnecessary lines.

2019-03-30 22:40 UTC, Creastery commented on src/main/resources/view/MainWindow.fxml
> +
Avoid unnecessary lines.

2019-03-30 22:40 UTC, Creastery commented on src/main/java/seedu/address/ui/RequirementCategoryCard.java
> +                .reduce(0, (left, right) -> left + right);
This assignment is overly complex.

You can split it into two:
```java
Stream<Module> modulesInRequirementCategory = requirementCategory.getCodeSet().stream()
        .map(code -> moduleList.stream().filter(module -> module.getCode().equals(code)).findFirst().get());

int currentCredits = modulesInRequirementCategory.map(Module::getCredits).map(Credits::toString)
        .map(Integer::parseInt).reduce(0, (creditsA, creditsB) -> creditsA + creditsB);
```

2019-03-30 22:40 UTC, Creastery commented on src/main/java/seedu/address/ui/RequirementCategoryCard.java
> +            requirementCategoryCredit.setStyle("-fx-text-fill: green;");
Perhaps toggle a class with the styles dynamically instead?

2019-03-30 22:40 UTC, Creastery commented on src/main/java/seedu/address/ui/RequirementCategoryCard.java
> +            noCodes.setFill(Color.WHITE);
See above comment.

2019-03-31 09:59 UTC, chyeo commented on src/main/java/seedu/address/logic/commands/RequirementListCommand.java
> +                    .map(Integer::parseInt).reduce(0, (left, right) -> left + right);
Roger, have renamed the left and right variable

2019-03-31 10:00 UTC, chyeo commented on src/main/java/seedu/address/model/AddressBook.java
> +    public Module hasModule(Code code) {
Will take note, and rephrase the statement accordingly

2019-03-31 10:00 UTC, chyeo commented on src/main/java/seedu/address/logic/commands/RequirementListCommand.java
> +            requirementListContent.append(requirementCategory.getName() + " \n");
Thank you for the feedback, will change the StringBuilder accordingly.

2019-03-31 10:06 UTC, chyeo commented on src/test/java/seedu/address/logic/commands/RequirementListCommandTest.java
> +            requirementListContent.append(requirementCategory.getName() + " \n");
Roger, have made changes to it,

2019-03-31 14:33 UTC, Creastery commented on src/main/java/seedu/address/ui/RequirementCategoryCard.java
> +        if (currentCredits > Integer.parseInt(requirementCategory.getCredits().toString())) {
Since `requirementCategory.getCredits().toString()` is used multiple times here, perhaps you can extract it to a variable.

2019-03-31 16:06 UTC, Creastery requested changes

2019-03-31 16:06 UTC, Creastery commented on src/main/java/seedu/address/ui/MainWindow.java
> +                logic.getFilteredModuleList());
This should be `logic.getAddressBook().getModuleList()`.
There's edge cases in your current implementation.

2019-03-31 17:06 UTC, lycjackie approved these changes
LGTM.

Let's wait @Creastery to finish his review.

2019-03-31 17:09 UTC, Creastery approved these changes
LGTM. Approving and merging.

2019-03-31 17:13 UTC, merged