DegreePlanner: implement `planner_move` command
CS2113-AY1819S2-T09-1/main pull request #136
Opened 2019-03-29 14:34 UTC by truegitnovice

Resolves #93 

The current implementation does not allow users to be able to move a module that has been added to a degree plan from one to another degree plan.

Let's implement a `planner_mode` command to allow users to move a module in a degree plan.

2019-03-30 17:19 UTC, Creastery commented
Sorry, I haven't had time to review your PR.
Anyhow, @lycjackie can you help to take a look to ensure that the Logic component makes sense for the this implementation?

2019-03-30 19:41 UTC, lycjackie requested changes

2019-03-30 19:41 UTC, lycjackie commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +            return new CommandResult(String.format(MESSAGE_SUCCESS, toMove, destinationYear, destinationSemester));
Correct me if I'm wrong...
I suppose this check is meant for if the source and destination planner is the same.

You are displaying `MESSAGE_SUCCESS` 

If your plan is to allow the scenario, perhaps you might want to consider remove the checks and continue the execution as per normal.

Basically, try to reduce the code duplication.

If you are disallowing this scenario, perhaps you might want to display an error message?

2019-03-30 19:41 UTC, lycjackie commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +        model.moveDegreePlanner(sourcePlanner, editedSourcePlanner, destinationPlanner, editedDestinationPlanner);
You might want to consider re-using your setDegreePlanner instead of creating a new function.

After all, `move` is a clone then `edit` (a.k.a delete then add)

2019-03-30 19:41 UTC, lycjackie commented on src/main/java/seedu/address/model/AddressBook.java
> +     *
Try not to rely too much on autoformat.

It will always create this additional line issues. 

Check your staging file before you commit :P

2019-03-30 19:41 UTC, lycjackie commented on src/main/java/seedu/address/model/AddressBook.java
> +    void moveDegreePlanner(DegreePlanner sourcePlanner, DegreePlanner editedSourcePlanner,
As mention above, you might want to consider using `setDegreePlanner(...)` directly since the method is already there.

2019-03-30 19:41 UTC, lycjackie commented on src/test/java/seedu/address/logic/commands/PlannerMoveCommandTest.java
> +    public void executeUndoRedo_validPlannerUnfilteredList_success() throws Exception {
You might want to consider testing for undo/redo together with the above unit tests.

i.e. At line 74.

This is because since you already have a successful moved, could have added the 4 new lines to test for undo/redo.

2019-03-30 22:19 UTC, Creastery requested changes

2019-03-30 22:19 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +        DegreePlanner sourcePlanner = model.getDegreePlannerByCode(toMove);
Since you are only using this method once in `PlannerMoveCommand`, there is no need to extract this to an method of `AddressBook`.

2019-03-30 22:19 UTC, Creastery commented on src/main/java/seedu/address/model/AddressBook.java
> +    public DegreePlanner getDegreePlanner(Year year, Semester semester) {
This creates unnecessary coupling between `AddressBook` and `Year`/`Semester`.
You can remove this coupling by just doing a stream filter like what you did in `UniqueDegreePlannerList#getDegreePlanner(...)`.

2019-03-30 22:19 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/PlannerMoveCommandTest.java
> +        Semester destinationSemester = new Semester("2");
Just to be consistent, perhaps rename `destinationYear` -> `validYear` and `destinationSemester` -> `validSemester`.

2019-03-30 22:19 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/PlannerMoveCommandTest.java
> +        Semester destinationSemester = new Semester("2");
See above comment.

2019-03-30 22:19 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/PlannerMoveCommandTest.java
> +        Semester destinationSemester = new Semester("1");
See above comment.

2019-03-30 22:19 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/PlannerMoveCommandTest.java
> +        Semester destinationSemester = new Semester("2");
See above comment.

2019-03-30 22:19 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/PlannerMoveCommandTest.java
> +        Semester destinationSemester = new Semester("2");
See above comment.

2019-03-31 01:45 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +            return new CommandResult(String.format(MESSAGE_SUCCESS, toMove, destinationYear, destinationSemester));
Thanks for the suggestion.
I am allowing the scenario. 
I have modified the code to reduce the code duplication.
However, I have not removed the check due to how `setDegreePlanner` is implemented which prevents the scenario.

2019-03-31 01:46 UTC, truegitnovice commented on src/main/java/seedu/address/model/AddressBook.java
> +     *
Oops. Thanks for catching it.

2019-03-31 01:49 UTC, truegitnovice commented on src/test/java/seedu/address/logic/commands/PlannerMoveCommandTest.java
> +    public void executeUndoRedo_validPlannerUnfilteredList_success() throws Exception {
Thank you for the suggestion. I have made the change accordingly.
I didn't do so as I thought they shouldn't belong to the same category as one test valid arguments and the other test if undo/redo works. 
After a second thought, since the test  `execute_validPlannerUnfilteredList_success` doesn't necessarily implies 'test valid arguments', I think it is better to do so as you mentioned.

2019-03-31 01:50 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +        DegreePlanner sourcePlanner = model.getDegreePlannerByCode(toMove);
Thank you for the suggestion. I have remove the `getDegreePlanner` method and made changes as you suggested.

2019-03-31 10:15 UTC, Creastery requested changes

2019-03-31 10:15 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +            model.commitAddressBook();
Assuming that there is CS1010 in Year 1 Semester 1 of the degree plan:
Executing `planner_move year/1 sem/1 code/CS1010` will be successful.
However, executing an `undo` command after that will result in "No commands to undo", which is incorrect.
`model.commitAddressBook()` should be moved out of this if statement.

2019-03-31 10:37 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +            model.commitAddressBook();
Thank you for the catch!

2019-03-31 11:10 UTC, Creastery requested changes

2019-03-31 11:10 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
> +        DegreePlanner destinationPlanner = model.getFilteredDegreePlannerList().stream()
Should be using `model.getAddressBook().getDegreePlannerList()` instead of `model.getFilteredDegreePlannerList()` here.

2019-03-31 13:49 UTC, Creastery approved these changes

2019-03-31 13:56 UTC, Creastery commented on src/main/java/seedu/address/model/Model.java
> +    DegreePlanner getDegreePlannerByCode(Code code);
Comments don't match the method!

2019-03-31 14:12 UTC, truegitnovice commented on src/main/java/seedu/address/model/Model.java
> +    DegreePlanner getDegreePlannerByCode(Code code);
Sorry for this silly mistake. Thank you so much for spotting!

2019-03-31 14:36 UTC, Creastery commented
LGTM. Let's wait for @lycjackie to review.

2019-03-31 14:36 UTC, lycjackie approved these changes

2019-03-31 14:37 UTC, lycjackie commented
LGTM. Thanks for the hard work!

2019-03-31 14:38 UTC, merged

2019-03-31 15:02 UTC, truegitnovice commented
Thank you for the amazing reviews!