docs/DeveloperGuide: update 'planner_move' command
CS2113-AY1819S2-T09-1/main pull request #154
Opened 2019-04-01 15:24 UTC by truegitnovice

Currently, DeveloperGuide is lacks information on 'planner_move'
command.

Let's update DeveloperGuide to include more information so that
the readers will be able to have better idea about 'planner_move'
command.

2019-04-01 15:31 UTC, chyeo requested changes

2019-04-01 15:31 UTC, chyeo commented on docs/DeveloperGuide.adoc
> +If all checks are passed, `PlannerMoveCommand` will update the context in `ModelManager` through `setDegreePlanner`.
should change this to all `If all checks pass`

2019-04-01 15:40 UTC, chyeo approved these changes
LGTM. Thank you for updating the Developer Guide.

2019-04-01 15:40 UTC, merged

2019-04-02 04:36 UTC, truegitnovice commented
Thanks for the quick review.