Planner_add command enhancement
CS2113-AY1819S2-T09-1/main pull request #161
Opened 2019-04-02 10:08 UTC by WendyBaiYunwei

Current `planner_add` command does not support addition of Co-requisites.
Meanwhile, there lacks a check for null.

These problems respectively make adding of Co-requisites troublesome, and the programme not secure enough.

Let's make planner_add support `Co-requisites` and add in a check for a `DegreePlanner` object that may return null when a `DegreePlanner` with a certain `Year` and `Semester` is not found.

* [1/2] [planner_add: implement coreq for planner_add] (https://github.com/CS2113-AY1819S2-T09-1/main/commit/73eb89d700873ab9f5ce0eea961d8bdf42f487bd)

* [2/2] [planner_add:prevent null pointer exception] (https://github.com/CS2113-AY1819S2-T09-1/main/commit/31c7d9fa0d33d02428b3d6d8a3e4137c9fbe2a15)

2019-04-03 08:42 UTC, Creastery requested changes

2019-04-03 08:42 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +
Remove unnecessary addition of newline.

2019-04-03 08:42 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> -    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
Why are all the messages made `private`?

2019-04-03 08:42 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +    private static final String COREQ_MESSAGE_SUCCESS = "\nCo-requisite(s) added:\n%1$s";
This should be within `MESSAGE_SUCCESS`. 
When no co-requisites are added, simply supply "None" to the format string.

2019-04-03 08:42 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +            + "%2$s does not exist.";
Let's keep variables more concise and consistent.
`MESSAGE_NONEXISTENT_MODULES` and `MESSAGE_NONEXISTENT_DEGREE_PLANNER` are more intuitive.

2019-04-03 08:42 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        for (Code codeToAdd :codesToAdd) {
Please add space after `:`.

2019-04-03 08:42 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +            if (module.getCorequisites().size() > 0) {
This if statement check is redundant since `addAll()` does nothing on an empty set anyways.

2019-04-03 08:42 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        coreqAdded.removeAll(codesToAdd);
Isn't `coreqAdded` going to be equivalent to `selectedCodeSet.removeAll(codesToAdd)`?
If so, you could just do:
```java
Set<Code> coreqAdded = new HashSet<>(selectedCodeSet);
coreqAdded.removeAll(codesToAdd);
```

2019-04-03 10:49 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> -    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
I have changed the messages to public. 
But I changed them to private initially because I didn't think they were necessary to be public, since they are used inside the command class only. As we should keep the access modifier as private as possible, I changed them to private.

2019-04-03 10:53 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> -    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
I see. Do note that these message variables need to have `public` access modifiers so that you can refer to them in your unit tests!

2019-04-03 11:00 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> -    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
Anyway, I changed them back to private still because at least for now, these 3 messages will not be used elsewhere. Please just inform me if it is necessary to change back.

2019-04-03 11:03 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> -    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
I think you can set the all the messages as `public`, since you will need to create unit tests to test the logic involving the excluded messages sooner or later.

2019-04-03 11:16 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> -    public static final String MESSAGE_MODULE_DOES_NOT_EXIST = "The module(s) %1$s do not exist in the module list.";
Somehow missed out your comment. I have changed them back. I got something urgent on now and cannot double check again. The tag will still be ongoing. If you feel that the changes meet the review requirement, please directly help me merge. If not, I will come back and double check again. please ignore this message if you have no time now.

2019-04-03 14:28 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        coreqAdded.removeAll(codesToAdd);
Sorry after changing I realised that perhaps you misunderstood the code. selectedCodeSet contains all the codes in the selected degree planner. When directly adding in all the selectedCodeSet, all the codes that are not Co-req themselves will be added in as well, which is not what we want.

2019-04-03 14:44 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
> +        coreqAdded.removeAll(codesToAdd);
Oh okay. In that case, then you can simplify:

https://github.com/CS2113-AY1819S2-T09-1/main/blob/7a97f009b683f2a443190981801685769f8e3886/src/main/java/seedu/address/logic/commands/PlannerAddCommand.java#L90-L103

into:

```java
Set<Code> selectedCodeSet = new HashSet<>(selectedDegreePlanner.getCodes());
selectedCodeSet.addAll(codesToAdd);
codesToAdd.stream().map(model::getModuleByCode).map(Module::getCorequisites).forEach(selectedCodeSet::addAll);

Set<Code> coreqAdded = new HashSet<>(selectedCodeSet);
coreqAdded.removeAll(codesToAdd);
```

2019-04-03 14:48 UTC, Creastery requested changes

2019-04-03 14:48 UTC, Creastery commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
>          model.commitAddressBook();
You are updating only 1 degree planner here.
If the co-requisites you are adding over to this year & semester already exists in other years & semesters, there will be duplicate entries since the existing `DegreePlanner` for the other years & semesters are not updated.

2019-04-03 18:10 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerAddCommand.java
>          model.commitAddressBook();
Upon reviewing the code just now, I also realised the same problem. To resolve the issue, I threw a command exception and asked the users to move/remove the code(s) involved in order to proceed.

2019-04-08 11:51 UTC, WendyBaiYunwei commented
The code for dealing with coreqs left out is maintained. though its function will be invisible in the current version, it can help with future modification of the application.

2019-04-08 12:32 UTC, Creastery requested changes

2019-04-08 12:32 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java
> +            + " have to be in the same year and semester of the degree plan.";
`Co-requisites(s)` should be in lowercase.
`Modules that are Co-requisites to each other have to..` should be `Co-requisites modules have to...`

2019-04-08 12:32 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java
> +            + "%2$s does not exist.";
Should be:
```
Year %1$s Semester %2$s does not exists in the degree plan!
```

2019-04-08 12:32 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java
> -
Please add back the line here.
The line is used to separate pre-condition(s) from the remaining code.

2019-04-08 12:32 UTC, Creastery commented on src/test/java/pwe/planner/logic/parser/PlannerAddCommandParserTest.java
> +                + PREFIX_CODE + null, Code.MESSAGE_CONSTRAINTS);
This test doesn't make sense.

2019-04-12 18:01 UTC, Creastery requested changes

2019-04-12 18:01 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java
> +                .collect(Collectors.joining(", "));
This should be declared within the `if` statement.

2019-04-12 18:01 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java
> +                .collect(Collectors.joining(", "));
This should be declared within the `if` statement.

2019-04-12 18:01 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerAddCommand.java
> +                throw new CommandException(String.format(MESSAGE_INVALID_COREQ, invalidDuplicateCoreqs, codesToAdd));
You're lacking `.stream().map(Code::toString).collect(Collectors.joining(", "))` for `invalidDuplicateCoreqs` and `codesToAdd` here.

2019-04-14 07:03 UTC, Creastery approved these changes
LGTM. Approving and merging.

2019-04-14 07:05 UTC, merged