planner_remove: implement planner_remove command
CS2113-AY1819S2-T09-1/main pull request #162
Opened 2019-04-02 10:56 UTC by WendyBaiYunwei

#160 
Let's implement `planner_remove` to enable the users to remove module(s) and their Co-requisites.

2019-04-03 10:07 UTC, Letm3through requested changes

2019-04-03 10:07 UTC, Letm3through commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +    private static final String MESSAGE_SUCCESS = "Removed module(s) from the degree plan:\n%1$s";
Is there any reason why the messages are all `private` instead of `public`?

2019-04-03 10:07 UTC, Letm3through commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +    private static final String COREQ_MESSAGE_SUCCESS = "\nCo-requisite(s) removed:\n%1$s";
You should combine this with `MESSAGE_SUCCESS`. Right now when co-requisites are removed, the message displayed seems awkward since `Co-requisites removed` are `Removed module(s) from the degree plan` too.

2019-04-03 10:07 UTC, Letm3through commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +    private static final String MESSAGE_CODE_DOES_NOT_EXIST = "The module(s) %1$s does not exist in the degree plan.";
Can we be more consistent and use `MESSAGE_NONEXISTENT_MODULES` instead?

2019-04-03 10:07 UTC, Letm3through commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +    public PlannerRemoveCommand(Set<Code> plannerCodes) {
I think in order to be consistent, you may want to consider renaming it as `codes` instead.

2019-04-03 10:07 UTC, Letm3through commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +        if (coreqRemoved.size() > 0) {
Once you combine `MESSAGE_SUCCESS` and `COREQ_MESSAGE_SUCCESS`, you can combine these two too.

2019-04-03 10:07 UTC, Letm3through commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +                //Removes the Co-requisite(s) of module(s) that exists in the degree plan.
Can this comment be more clear? Sounds like removing the field `co-requisites` of modules in the `moduleList`.

2019-04-03 10:07 UTC, truegitnovice commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +        for (DegreePlanner selectedDegreePlanner : degreePlannerList) {
Just Suggestion: Perhaps, instead of looping though all `degreePlanner` in the `degreePlannerList`, you can consider utilizing `getDegreePlannerByCode` method in the `AddressBook` and loop inside only `degreePlanners` that are relevant. The choice you make will rely on assumption you make.

2019-04-04 00:23 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +    private static final String MESSAGE_SUCCESS = "Removed module(s) from the degree plan:\n%1$s";
I was thinking that the messages were not used elsewhere, and I needed to keep them as private as possible. However, I forgot abt the test

2019-04-04 00:25 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +    private static final String MESSAGE_CODE_DOES_NOT_EXIST = "The module(s) %1$s does not exist in the degree plan.";
I changed to MESSAGE_NONEXISTENT_CODES

2019-04-04 00:30 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +        if (coreqRemoved.size() > 0) {
I did not combine these two because it is necessary to differentiate the conditions where there are Coreq, and there is no Coreq.

No Coreq condition indicates that the Coreq added is "none", thus it has a different parameter as "none" is a string. The string "none" should not be mixed up with module(s) in my opinion

2019-04-04 00:34 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +                //Removes the Co-requisite(s) of module(s) that exists in the degree plan.
As @Creastery said last time, the entire Application can be viewed as a "degreePlanner". Thus, I thought that the planner section has been renamed to "degreePlan". However, if we do this, we may need to refactor the "degreePlanner" to "degreePlan". Let's check with @Creastery

2019-04-04 00:38 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +        for (DegreePlanner selectedDegreePlanner : degreePlannerList) {
I do not think it is necessary to do this since there are very few degreePlanners. But thanks for your suggestion!

2019-04-04 02:42 UTC, WendyBaiYunwei commented on src/main/java/seedu/address/logic/commands/PlannerRemoveCommand.java
> +                //Removes the Co-requisite(s) of module(s) that exists in the degree plan.
Anyway, I modified the code already and the original comment is gone.

2019-04-08 06:12 UTC, WendyBaiYunwei commented
Do u want to just name the degree plan back to degree planner? According to planner definition, planner can be “a list with info that is an aid to planning”. While the whole app is helping us to plan, the list of semesters is still a planner. So how abt we just call PWE application and the list planner? I dont think its wrong and no one will be fussy over this.
Because our code are all named as planner also
If you agree, then I will change the messages back to "degree planner"

2019-04-08 07:15 UTC, Creastery commented
> Do u want to just name the degree plan back to degree planner? According to planner definition, planner can be “a list with info that is an aid to planning”. While the whole app is helping us to plan, the list of semesters is still a planner. So how abt we just call PWE application and the list planner? I dont think its wrong and no one will be fussy over this.
> Because our code are all named as planner also
> If you agree, then I will change the messages back to "degree planner"

This has already been discussed many times, and the consensus was to use `degree plan` in UI / command results when there could be different interpretations of `degree planner`.

Say we use `degree planner` and `degree plan` interchangeably, and all UI / command results use the term `degree planner`.

When a new user runs `planner_remove`, they are shown the command usage:
```
Removes module(s) from the degree planner
```

Here, they may be confused as `degree planner` can refer to the entire application. 
In such interpretation, removed module(s) from the `degree planner` could also mean removing the entire module completely from the application. But clearly, that's not the intentions of the command, as it simply removes the module from the `degree plan` only.

This is simply done to avoid confusing our users.

2019-04-08 16:52 UTC, Letm3through requested changes

2019-04-08 16:52 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +        if (nonExistentPlannerCodes.size() > 0) {
Why not just use `!nonExistentPlannerCodes.isEmpty()`?

2019-04-08 16:52 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +    public static final String MESSAGE_SUCCESS = "Removed module(s) from the degree plan:\n%1$s\n"
Maybe it will be better for the app to have no newline here and have space instead?
If I am not wrong, other commands are doing so.
`Removed module(s) from the degree plan: %1$s\n`

2019-04-08 16:52 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +            + "Co-requisite(s) removed:\n%2$s";
Same thing as above.

2019-04-08 16:52 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +        if (coreqsRemoved.size() > 0) {
You can use string and `..?"None":...` to remove the repeated code by making to something like `return new CommandResult(String.format(MESSAGE_SUCCESS, codesToRemove,coreqsRemovedContent));`

2019-04-08 16:52 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/parser/PlannerRemoveCommandParser.java
> +                || !argMultimap.getPreamble().isEmpty()) {
I think this can be put in a line with line no.26.

2019-04-08 16:52 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/parser/PlannerRemoveCommandParser.java
> +    private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
**Please do follow the upstream.** 
There is no need to create `private static boolean arePrefixesPresent` here.
Please refer to `ParserUtil`.

2019-04-08 16:52 UTC, truegitnovice commented on src/test/java/pwe/planner/logic/commands/PlannerRemoveCommandTest.java
> +                new UserPrefs());
Can you reduce these lines together into lesser line?

2019-04-08 16:52 UTC, truegitnovice commented on src/test/java/pwe/planner/logic/commands/PlannerRemoveCommandTest.java
> +        assertEquals(String.format(PlannerRemoveCommand.MESSAGE_SUCCESS, validCodeSet, "None"),
Why not use `assertCommandSuccess`?
Is there any reason for using `assertEquals`?

2019-04-08 16:52 UTC, truegitnovice commented on src/test/java/pwe/planner/logic/commands/PlannerRemoveCommandTest.java
> +        thrown.expectMessage(String.format(PlannerRemoveCommand.MESSAGE_NONEXISTENT_CODES, nonexistentCodeSet));
Why is there `thrown` here?? Did you meant to use `assertCommandFailure`??

2019-04-10 02:05 UTC, WendyBaiYunwei commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +    public static final String MESSAGE_SUCCESS = "Removed module(s) from the degree plan:\n%1$s\n"
if you check add and remove commands, newline is used

2019-04-10 02:16 UTC, WendyBaiYunwei commented on src/test/java/pwe/planner/logic/commands/PlannerRemoveCommandTest.java
> +                new UserPrefs());
I dont have enough LoC and I believe that the current version is acceptable

2019-04-11 07:57 UTC, Letm3through requested changes
As we have discussed, I think there are still rooms for improvements in some command exception.
If it is possible, it will be nicer to comment some of commands or reduce the complexity. 
I will be tagging @chyeo to help me with a review since he has worked on `requirement_add` feature which has some similar logic involved and hence, he might have better overview and find anything I might have missed out.

2019-04-11 08:49 UTC, chyeo requested changes

2019-04-11 08:49 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +    public static final String MESSAGE_NONEXISTENT_CODES = "The module(s) %1$s does not exist in the degree plan.";
Perhaps you might want to change this error message so that it standardizes with the `add` and `delete` command?
`"The module(s) (%1$s) does not exist in the degree plan!"`

2019-04-11 08:49 UTC, chyeo commented on src/test/java/pwe/planner/logic/commands/PlannerRemoveCommandTest.java
> +        Model expectedModel = new ModelManager(
As you have declared the model in the `setUp()` method, you should change it to the following:
`Model expectedModel = new ModelManager(model.getApplication(), new UserPrefs());`

2019-04-11 08:49 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +        for (DegreePlanner selectedDegreePlanner : degreePlannerList) {
Is it possible to simplify this? Cause right now it looks very complicated.

2019-04-11 12:10 UTC, WendyBaiYunwei commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +    public static final String MESSAGE_NONEXISTENT_CODES = "The module(s) %1$s does not exist in the degree plan.";
Thank you for your suggestion. but add and delete is only single module, while planner_add and remove are multiple modules, so there will be bracket since the parameter is a set

2019-04-11 12:36 UTC, WendyBaiYunwei commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +        for (DegreePlanner selectedDegreePlanner : degreePlannerList) {
I added in more comments

2019-04-12 03:25 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +    public static final String MESSAGE_NONEXISTENT_CODES = "The module(s) %1$s does not exist in the degree plan.";
@WendyBaiYunwei You can try using `stream`, covert to `String` then `collect`.
For e.g.
```
String modulesContent = modules.stream().sorted().map(Code::toString).collect(Collectors.joining(", "));```

2019-04-12 03:44 UTC, Letm3through requested changes
Please make the changes indicated. 
I think you have not pushed some of the new changes according to the most recent [changes](https://github.com/CS2113-AY1819S2-T09-1/main/pull/162/files/97b0ee60eeb1416df23515984e3f11bdca287634..9b874d33af941ff478bf212807361eb1f2833cb6) you pushed.
Hence, I have resolved a request that you marked it as resolved.
Please label `status.ToReview` only when you have pushed all the latest commits.
If not, other reviewers will have to take a look and repeat the redundant processes of marking unchanged requests.

2019-04-12 03:44 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +        for (DegreePlanner selectedDegreePlanner : degreePlannerList) {
I think maybe you have forgot to push the changes.
There is no new comments added according to the [recent changes](https://github.com/CS2113-AY1819S2-T09-1/main/pull/162/files/97b0ee60eeb1416df23515984e3f11bdca287634..9b874d33af941ff478bf212807361eb1f2833cb6) you have made

2019-04-12 03:44 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/parser/PlannerRemoveCommandParser.java
> +
You may want to remove this line since it is redundant.

2019-04-12 03:44 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +    public static final String MESSAGE_SUCCESS = "Removed module(s) from the degree plan:\n%1$s\n"
I think you meant `delete` command right?
This is because `add` and `delete` command will display the information of the modules too.
Hence, it will need the new line.
However, for you case, you are only printing the module codes.
Therefore, you may want to be consistent with other more similar commands such as `planner_move` or `requirement_remove` which is ongoing.
Also use the [method](https://github.com/CS2113-AY1819S2-T09-1/main/pull/162/files/17d96e030e3e301da14f73417ea9b71feb77d792#r274748522) I mentioned to remove the brackets.

2019-04-13 17:28 UTC, Letm3through requested changes

2019-04-13 17:28 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +            + "Parameters: "
Could you change this?
```suggestion
            + "Format: " + COMMAND_WORD + " "
```

2019-04-13 17:28 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +            + " degree plan.";
Can you make this message more user friendly? Make use of `you`, `Perhaps`, etc.

2019-04-13 17:28 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +        for (DegreePlanner selectedDegreePlanner : degreePlannerList) {
```suggestion
        for (DegreePlanner degreePlanner : degreePlannerList) {
```
I think better to refactor

2019-04-13 17:28 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +            codesToRemove.stream().map(model::getModuleByCode).map(Module::getCorequisites)
Why do you need to find co-requisites of modules every single time in every single `selectedDegreePlanner`??
You are doing `Adds co-requisites of codes to remove to a set.` for every `codesToRemove`.
This should not be done in the loop.

2019-04-13 17:28 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +
```suggestion
String corequisitesRemovedContent = coreqsRemoved.isEmpty() ? "None" : coreqsRemoved.stream().map(Code::toString)
                        .collect(Collectors.joining(", "));
```

2019-04-13 17:28 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +                removedCodesString, coreqsRemoved.isEmpty() ? "None" : coreqsRemoved.stream().map(Code::toString)
```suggestion
                removedCodesString, corequisitesRemovedContent));
```

2019-04-13 17:28 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +                        .collect(Collectors.joining(", "))));
```suggestion
```

2019-04-13 23:20 UTC, WendyBaiYunwei commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +            + " degree plan.";
I checked with wei lin and he was alright with the planner_add messages. The reason I stuck to this was because I felt the original message itself is self-explanatory and concise. "Perhaps xxx" seemed redundant to me... Let us check with @Creastery

2019-04-13 23:24 UTC, WendyBaiYunwei commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +            + " degree plan.";
I understand that it is better for CH and me to be consistent. However, CH told me last time that he also did not really know how to make certain parts of the message more friendly.

2019-04-14 02:25 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerRemoveCommand.java
> +            + " degree plan.";
As previously discussed in person, our command messages should be more welcoming
What happens if the module code doesn't exists in the degree plan?
What should the user do here?
If we are able to provide a one-liner tip here, we should do it.

2019-04-14 11:45 UTC, Creastery approved these changes
LGTM. Approving and merging.

2019-04-14 11:45 UTC, Letm3through approved these changes

2019-04-14 11:47 UTC, chyeo approved these changes

2019-04-14 11:47 UTC, merged