RequirementCategory: implement `requirement_move` command
CS2113-AY1819S2-T09-1/main pull request #171
Opened 2019-04-04 11:19 UTC by chyeo

Resolves #169.

Currently our application does not allow users to move the modules that
have been added to requirement categories.

This makes it difficult for users when they are moving the modules in
the requirement category around. They would have to delete and add the
modules multiple times during the moving process.

To address these issues, let's add the 'requirement_move' command to
allow users to move modules in the requirement category.

First, let's implement the logic to handle how the modules are going to
be moved from one requirement category to another.

2019-04-08 08:54 UTC, lycjackie approved these changes
LGTM

I shall add @Creastery as reviewer for the model part.

2019-04-11 03:19 UTC, Creastery requested changes

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +        requirementCategories = model.getApplication().getRequirementCategoryList();
Why is `requirementCategories` a class attribute?
You are not using the variable elsewhere, so you should limit the scope of the variable to this method only.

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                   .map(Code::toString).collect(Collectors.joining(", "));
Here you are essentially repeating the same logic just to get the module codes.
Why not do it as such:
```java
Stream<Module> nonExistentCodes = toMove.stream().filter(code -> !model.hasModuleCode(code));
if (nonExistentCodes.count() > 0) {
    String nonExistentCodesErrorMessage = toMove.map(Code::toString).collect(Collectors.joining(", "));
    throw new CommandException(String.format(MESSAGE_NONEXISTENT_CODE, nonExistentCodeErrorMessage));
}
```

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                .anyMatch(requirementCategory -> requirementCategory.getCodeSet().contains(code)));
Indentation for nested lambda expressions is wrong.
Should have an additional indentation block at line 78.

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                    .map(Code::toString).collect(Collectors.joining(", "));
See previous comment on repetitive code logic and how you can simplify it.

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                (Collectors.joining(", ")), destinationRequirementCategory.getName()));
Should move `.collect` to Line 127, or extract out the second argument to `String.format(...)` as a variable to remain consistent with the rest of your method.

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +        if (singleSourceRequirementCategory != null) {
What is the rationale for specifically handling the case of moving module codes from a single requirement category?
Slight performance boost?

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                                    .getRequirementCategoryWithCodeAdded(destinationRequirementCategory, code);
This can be compressed to 2 lines only.

2019-04-11 03:19 UTC, Creastery commented on src/main/java/pwe/planner/model/util/RequirementCategoryUtil.java
> +     * Returns a RequirementCategory for the RequirementMoveCommand {@code RequirementMoveCommand}
Using the same comment for all 4 methods in this class doesn't help to understand what the method is doing!

2019-04-11 03:19 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +                new UserPrefs());
Compress this to 3 lines.

2019-04-11 11:33 UTC, chyeo commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +                new UserPrefs());
Have compressed the statments to 3 lines.

2019-04-11 11:33 UTC, chyeo commented on src/main/java/pwe/planner/model/util/RequirementCategoryUtil.java
> +     * Returns a RequirementCategory for the RequirementMoveCommand {@code RequirementMoveCommand}
The comments for the methods have been changed.

2019-04-11 11:34 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                                    .getRequirementCategoryWithCodeAdded(destinationRequirementCategory, code);
Have compressed the statments

2019-04-11 11:34 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +        if (singleSourceRequirementCategory != null) {
Yes. as we are moving from a single source to destination.
The alternative method would be to loop through all the codes specified by the user.

2019-04-11 11:35 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                (Collectors.joining(", ")), destinationRequirementCategory.getName()));
Have extracted out the `collector` to the `RequirementCategoryUtil`

2019-04-11 11:35 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +        requirementCategories = model.getApplication().getRequirementCategoryList();
Have moved the variable down to the method

2019-04-11 11:36 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                .anyMatch(requirementCategory -> requirementCategory.getCodeSet().contains(code)));
Have removed this method and replaced it with another piece of code

2019-04-11 11:36 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                   .map(Code::toString).collect(Collectors.joining(", "));
Roger, will simplify the affected codes

2019-04-11 11:37 UTC, chyeo commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +                    .map(Code::toString).collect(Collectors.joining(", "));
Roger, the codes have been simplified

2019-04-12 01:17 UTC, Creastery requested changes

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +        String formattedCodeString = toMove.stream().map(Code::toString).collect(Collectors.joining(", "));
`formattedCodeString` -> `codesMoved`

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +            + "Perhaps you were trying to add modules into the requirement category?";
The correct command `requirement_add` should be mentioned here to inform the user what command to use to add modules to a requirement category!.

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +            + "Afterwards, add the module into a requirement category.\n"
Same as above.

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +            + "Then you will be able to move the module around the requirement categories!";
This line is not necessary since you are providing a tip that assumes that the module does not exists in the application.

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/model/util/RequirementCategoryUtil.java
> +     * Returns a requirement category object with the specified code {@code toMove} removed from the
Returns a **new** requirement category...

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/model/util/RequirementCategoryUtil.java
> +     * Returns a requirement category object with the specified code set {@code toMove} removed from the
Same as above.

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/model/util/RequirementCategoryUtil.java
> +     * Returns a requirement category object with the specified code {@code toMove} added from the
Same as above.

2019-04-12 01:17 UTC, Creastery commented on src/main/java/pwe/planner/model/util/RequirementCategoryUtil.java
> +     * Returns a requirement category object with the specified code set {@code toMove} added from the
Same as above.

2019-04-12 01:17 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +        Set<Code> validCodeSet = new HashSet<>(Set.of(new Code("CS1231")));
There's no need to wrap `Set.of(...)` within `new HashSet<>(...)`!
Same goes for the remaining of this file.

2019-04-12 01:17 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +                        nonExistentRequirementCategoryName));
You can consider intialise the `command` and `expectedMessage` separately to keep the `assertCommandXYZ(...)` short.
Same goes for the remaining of this file.

2019-04-12 01:17 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +        sourceCodeSet1.add(new Code("CS2100"));
Could have just used `Set.of(...)` here.

2019-04-12 01:17 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +        sourceCodeSet2.add(new Code("CS1231"));
Same as above.

2019-04-12 01:17 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +        sourceCodeSet2.add(new Code("CS1231"));
Same as above.

2019-04-12 01:17 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/RequirementMoveCommandTest.java
> +        codeSetToCompare.add(new Code("CS1010"));
Same as above.

2019-04-12 17:48 UTC, Creastery requested changes

2019-04-12 17:48 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +            + "You can try adding the module into the requirement category using the 'requirement_add' command.";
Add a `[Tip]` in front of this sentence!

2019-04-12 17:48 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +            + "Afterwards, add the module into a requirement category.\n";
Can rephrase this to:
```
[Tip] You may want to add the module into the module list first using the "add" command.
Afterwards, you can add the module into the requirement category using the "requirement_add" command!
```

2019-04-12 17:48 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +            + "You can try adding the module into the requirement category using the 'requirement_add' command.";
`'requirement_add'` -> `"requirement_add"`

2019-04-13 21:32 UTC, Creastery requested changes

2019-04-13 21:32 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/RequirementMoveCommand.java
> +            + " in the application!";
Where can the user find this `requirement category list`?
I'd suggest to print the list of acceptable requirement category names here regardless.

2019-04-14 07:29 UTC, Creastery approved these changes
LGTM. Approving and merging.

2019-04-14 07:29 UTC, chyeo commented
Thanks for the review!

2019-04-14 07:33 UTC, merged