docs/DeveloperGuide: improve explanation for `find` feature.
CS2113-AY1819S2-T09-1/main pull request #172
Opened 2019-04-04 12:09 UTC by lycjackie

Let’s update the `DeveloperGuide` to improve our explanation to describe
the implementation better for our reader.

2019-04-08 06:02 UTC, Creastery requested changes

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +Step 2 and 3 is performed by `BooleanExpression#parse`
Should be `BooleanExpressionParser#parse(...)`

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +checks, the argument are passed to `BooleanExpressionParser` which handle the evaluation of the expression.
The mixed use of `input` and `argument` makes it confusing for readers.
I think you could simplify the second sentence by saying `FindCommandParser` calls `BooleanExpressionParser#parse(...)` to evaluate the expression.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +issues which they do not provide.
Capitalise `Java`.
Also, you need to rephrase the second half of the sentences.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +exists.
`do` -> `does`

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +issues which they do not provide.
Here you mentioned 3 issues, but there are only two below!

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +was invalid due to the missing `operator`
Having worked on this with you on the `StringTokenizer`, I think this could be better phrased.
Discuss more about how we still need to do additional parsing after using `StringTokenizer` to facilitate the execution of Shunting Yard.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +As such, our `Tokenizer` aim to solve these 2 issues.
`aim` -> `aims`.
Perhaps mentioned that we developed a custom `Tokenizer` that aims to solve these two issues.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +The table below shows the different of our `Tokenizer` vs `StringTokenizer` and `ArgumentMultimap`
`different` -> `differences`.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +|====
Since parenthesis is also considered as an operator, perhaps include it and talk about it briefly here.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> + `BooleanExpressionParser` which will initialise a new tokenizer which extract all argument as token. +
```
initialise a new tokenizer which extract all argument as token
```
should be:
```
initialize a new `Tokenizer` that extracts the arguments as tokens
```

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +With each token, the `BooleanExpressionParser` will then create a predicate for each prefix.
This should be:
```
`BooleanExpressionParser` will create a `Predicate` based on the `Prefix` in each token. If the token is an `Operator`, `BooleanExpressionParser` will apply the operator on two `Predicate` to combine them into a composite `Predicate.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +This sections share some design consideration we encounter when enhancing the existing `find` feature.
`share some design consideration we encounter` -> `details the design considerations we made`

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
>  application.
Might want to reorder the two points and remove this note.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +* Returns a very huge set of results when the keywords increase.
`keywords increase` -> `number of keywords increase`.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +* Find command will be restricted to logical `OR` results.
Could be better phrased.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> + that can parse complex boolean expression and composite the predicate.
You can't just `composite the predicate`. `Composite` isn't an action verb!

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +| *Pros* | Find command can be very flexible as per user wish.
Could go into a bit more details here.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +| *Cons* a|
Remove `a`.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +After weighing both approach pros and cons, we have decided to go with the *approach 2*. +
`we have decided` -> `we decided`.

2019-04-08 06:02 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +effectively. Which defeat the purpose of our application.
`Which defeat the purpose of our application` is a strong statement.
Perhaps you could say: 
```
drastically reduce the effectiveness of the `find` command
```

2019-04-08 07:01 UTC, lycjackie commented on docs/DeveloperGuide.adoc
> +| *Cons* a|
This is intended.

asciidoc 
`a| 
* point 1
* point 2
`

Allows the cells to have bullets point.

2019-04-11 13:20 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
>  The find feature aims to help users to be able to locate any module in our application easily. We support
I think it will be better to change this part too. 
```suggestion
The find feature aims to help users to be able to easily locate any module in our application. 
```

2019-04-11 14:06 UTC, Letm3through requested changes

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
>  The find feature aims to help users to be able to locate any module in our application easily. We support
I think it will be better to change this part too. 
```suggestion
The find feature aims to help users to be able to easily locate any modules in our application. 
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
>  the finding of module's name, code and credits. This enable our users to be able to find for any modules with partial
```suggestion
We support the finding of modules with their names, codes and credits. This enables our users to find any modules with partial
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> + knowledge about the module they need.
Do you mean this?
```suggestion
information of the modules they have.
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +`FindCommandParser` calls `BooleanExpressionParser#parse` which handle the evaluation of the expression.
```suggestion
`FindCommandParser` calls `BooleanExpressionParser#parse` which handles the evaluation of the expression.
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
>  2. `BooleanExpressionParser` handle the high-level syntax of the find expressions and map them into
```suggestion
2. `BooleanExpressionParser` handles the high-level syntax of the find expressions and maps them into
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +We found two main issues which could not be satisfy by either `StringTokenizer` or `ArgumentMultimap`.
```suggestion
We found two main issues which could not be satisfied by either `StringTokenizer` or `ArgumentMultimap`.
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +. `StringTokenizer` default delimiter is whitespace, although we could change the delimiter and parse multiple
```suggestion
. `StringTokenizer` has default delimiter as whitespace, although we could change the delimiter and parse multiple
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
>  This is represented by the class `pwe.planner.logic.parser.Operator` and define all valid operators to be used in
```suggestion
This is represented by the class `pwe.planner.logic.parser.Operator` and defines all valid operators to be used in
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +When the `FindCommandParser` received the provided user argument, after doing it checks, it will pass the argument to
Maybe you may want to elaborate more on what _checks_ is carried out?
```suggestion
When `FindCommandParser` receives the provided user argument, it will carry out checks and pass the argument to
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +==== Design Consideration
```suggestion
==== Design Considerations
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +This sections share details the design considerations we made when enhancing the existing `find` feature.
```suggestion
This section shares the design considerations we went through during the enhancement of the existing `find` feature.
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +*1.* Implement an algorithm https://en.wikipedia.org/wiki/Shunting-yard_algorithm[Shunting Yard] that parse the complex
```suggestion
*1.* Implement an algorithm https://en.wikipedia.org/wiki/Shunting-yard_algorithm[Shunting Yard] that parses the complex
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +The table below shows the comparison of different approach we could take.
```suggestion
The table below shows comparisons between the two implementations that could have been made.
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +* Requires a lot of tests to ensure expected behaviour
```suggestion
* Requires many tests to ensure expected behaviours
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +* Extra work required to integrate a new logic parser into `FindCommandParser` and may cause build problems if not
```suggestion
* Extra work is required to integrate a new logic parser into `FindCommandParser`. It may result in build problems if it is not
```

2019-04-11 14:06 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +Find command can be very flexible and scale with the application data.
Sounds quite vague.
```suggestion
Find command can be very flexible. It can work with many arguments to search for the specific modules that the user wants.
```

2019-04-11 14:06 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +After weighing both approach pros and cons, we decided to go with the *approach 1*. +
```suggestion
After weighing both pros and cons, we decided to go with the *approach 1*. +
```

2019-04-11 14:06 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +This is because we are expecting many common names between a module available in the university curriculum. If the
```suggestion
This is because we are expecting many similar names between modules available in the university curriculum. If the
```

2019-04-11 14:06 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +user could only search with an implicit logical `OR`, they would not be able to find a module which suit them
```suggestion
user could only search with an implicit logical `OR`, the user would not be able to find a module which suits the user's needs
```

2019-04-11 14:06 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +effectively. Which drastically reduce the effectiveness of the `find` command.
```suggestion
effectively. This can drastically reduce the effectiveness of the `find` command.
```

2019-04-13 10:47 UTC, Letm3through requested changes

2019-04-13 10:47 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +| Respect the order of delimiters. | Respect the order of delimiters | Only keep track which delimiters is present.
```suggestion
| Respect the order of delimiters. | Respect the order of delimiters | Only keep track which delimiters are present.
```

2019-04-13 10:47 UTC, Letm3through commented on docs/DeveloperGuide.adoc
> +After weighing both pros and cons, we decided to go with the *approach 1*. +
```suggestion
After weighing both pros and cons, we decided to go with *approach 1*. +
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +After many rounds of experiment with `StringTokenizer` provided by native Java and `ArgumentMultimap`. +
```suggestion
After many rounds of experiment with `StringTokenizer` that is provided by native Java and `ArgumentMultimap`. +
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +. `ArgumentMultimap` does not keep track of the order of each delimiter. They will only track if the delimiter provided
```suggestion
. `ArgumentMultimap` does not keep track of the order of each delimiter. They will only track if the delimiter is provided
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +. `StringTokenizer` has default delimiter as whitespace, although we could change the delimiter and parse multiple
```suggestion
. `StringTokenizer` has a default delimiter as a whitespace, although we could change the delimiter and parse multiple
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +This will return us 1 token. `name/AAAA code/BBBB`, which we could not use to check due to the missing `operator`. +
```suggestion
This will return us 1 token. `name/AAAA code/BBBB`, which we cannot use to check due to the missing `operator`. +
```
`cannot` since I believe it implies now too

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +. `StringTokenizer` can take in `PREFIX` as delimiter, however, this will split the argument (i.e. `code/CS1231`) into
You may want to add a newline after line 431 just like you did at other lines.

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +`BooleanExpressionParser`. These parsing creates more overhead as we have to ensure there are proper checks is done.
```suggestion
`BooleanExpressionParser`. This parsing creates more overhead as we have to ensure that proper checks are carried out.
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +The table below shows the differences of our `Tokenizer` vs `StringTokenizer` and `ArgumentMultimap`
```suggestion
The table below shows the differences among our `Tokenizer`, `StringTokenizer` and `ArgumentMultimap`
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +| Support multiple delimiters. | Support only multiple delimiters. | Support multiple delimiters.
```suggestion
| Support multiple delimiters. | Support multiple delimiters. | Support multiple delimiters.
```
Is there any reason why is there `only` in just that one?

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +| More flexible in splitting of token | Only split token based on delimiters | Does not split into token.
```suggestion
| Splitting tokens is more flexible | Only split token based on delimiters | Does not split into token.
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +The table below shows the valid operators our application currently support.
```suggestion
The table below shows the valid operators that our application currently support.
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +This sections shares the design considerations we went through during the enhancing the existing `find` feature.
```suggestion
This section shares the design considerations we went through during the enhancement of the existing `find` feature.
```

2019-04-13 10:47 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +user could only search with an implicit logical `OR`, the user would not be able to find a module which suit the
```suggestion
user could only search with an implicit logical `OR`, the user would not be able to find modules which suit the
```

2019-04-14 15:14 UTC, Creastery approved these changes
LGTM. Approving and merging.

2019-04-14 15:14 UTC, Letm3through approved these changes

2019-04-14 15:15 UTC, merged