planner_suggest: implement planner_suggest command
CS2113-AY1819S2-T09-1/main pull request #192
Opened 2019-04-05 02:31 UTC by WendyBaiYunwei

Closes #191 
Currently, users may not know what module(s) to put in the degree plan. 
Let's implement `planner_suggest` to facilitate recommendations of module(s) to add to the degree plan.

2019-04-11 04:32 UTC, WendyBaiYunwei commented
Planner_suggest has compulsory field "tag". This design is bad because not every module has a tag.
Let's remove the compulsory field and make it optional.

2019-04-11 12:37 UTC, lycjackie requested changes

2019-04-11 12:37 UTC, lycjackie commented on src/main/java/pwe/planner/logic/commands/PlannerSuggestCommand.java
> +        List<ModuleToSuggest> modulesToSuggest = new ArrayList<ModuleToSuggest>();
I believe the RHS of `<ModuleToSuggest>` is not needed here. (Mentioned by Intellij)

Same for the next few declaration

2019-04-11 12:37 UTC, lycjackie commented on src/main/java/pwe/planner/logic/commands/PlannerSuggestCommand.java
> +        model.commitApplication();
Why would you need to do this when there is no modification? 

Correct me if I'm wrong but planner_suggest is not doing any mutation of the data?

2019-04-11 12:37 UTC, lycjackie commented on src/main/java/pwe/planner/logic/commands/PlannerSuggestCommand.java
> +        modulesToSuggest.sort(new SortModulesToSuggest());
Do you really need a comparator class just to do this?

You could just create a private method to do the comparator or even a lambda function for this.

2019-04-11 12:37 UTC, lycjackie commented on src/main/java/pwe/planner/logic/commands/PlannerSuggestCommand.java
> +        }
The whole method actually can be simplified using the following code.
```
List<Code> codesWithMatchingTags = modulesWithMatchingTags.stream()
                .map(ModuleToSuggest::getModuleCode).collect(Collectors.toList());
```

2019-04-11 12:37 UTC, lycjackie commented on src/main/java/pwe/planner/logic/commands/PlannerSuggestCommand.java
> +    public CommandResult execute(Model model, CommandHistory history) throws CommandException {
`execute(...)` throws `CommandExceptions` yet is never throw? :O

2019-04-11 12:37 UTC, lycjackie commented
When testing out the command, the Module(s) with matching credits is not limiting to `MAX_NUMBER_OF_ELLEMENTS`

![image](https://user-images.githubusercontent.com/2564679/55957736-a042e100-5c99-11e9-80bc-a05deea56ae0.png)

Is this intended?

2019-04-11 12:43 UTC, lycjackie requested changes

2019-04-11 12:43 UTC, lycjackie commented on src/main/java/pwe/planner/model/planner/ModuleToSuggest.java
> +public class ModuleToSuggest {
Actually, for this class, do you think is possible to just use `Credits`, `Tags` and `Code` class directly?

2019-04-11 13:17 UTC, WendyBaiYunwei commented
> When testing out the command, the Module(s) with matching credits is not limiting to `MAX_NUMBER_OF_ELLEMENTS`
> 
> ![image](https://user-images.githubusercontent.com/2564679/55957736-a042e100-5c99-11e9-80bc-a05deea56ae0.png)
> 
> Is this intended?

The list of recommended modules is intended to be limited to 10 elements, but the modules with matching credits and tags are not limit to 10. Do you think it is acceptable?

2019-04-11 13:33 UTC, lycjackie commented
> > When testing out the command, the Module(s) with matching credits is not limiting to `MAX_NUMBER_OF_ELLEMENTS`
> > ![image](https://user-images.githubusercontent.com/2564679/55957736-a042e100-5c99-11e9-80bc-a05deea56ae0.png)
> > Is this intended?
> 
> The list of recommended modules is intended to be limited to 10 elements, but the modules with matching credits and tags are not limit to 10. Do you think it is acceptable?

Since the intention was to suggest to the user, maybe a filtered list would be better?

2019-04-14 11:37 UTC, lycjackie approved these changes

2019-04-14 11:37 UTC, Letm3through approved these changes

2019-04-14 12:03 UTC, merged