Logic: add `planner_show` Command
CS2113-AY1819S2-T09-1/main pull request #196
Opened 2019-04-06 14:59 UTC by truegitnovice

Resolves #96 

Currently, the application does not have the `planner_show` command that allow the user to see specific academic semesters that he/she wants.

Let's carry out the followings to allow the implementation of `planner_show`:

Note: As we have discussed, in order to reduce the confusion, we will be changing the command name from `planner_list` to `planner_show`.

2019-04-08 16:35 UTC, lycjackie reviewed
LGTM, logic seems pretty similar to how I did `find` command.

I can see that you make use of our generic `BooleanExpressionParser`!
Hope that it is easy to use for you too!

I will ask @Creastery  to review on the model.

2019-04-12 01:48 UTC, Creastery requested changes

2019-04-12 01:48 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerShowCommand.java
> +            COMMAND_WORD + ": Shows all academic semesters which satisfies the expression of search conditions "
`COMMAND_WORD` should go on Line 24.

2019-04-12 01:48 UTC, Creastery commented on src/main/java/pwe/planner/logic/parser/FindCommandParser.java
> +    private static final Logger logger = LogsCenter.getLogger(MainApp.class);
This should be `LogsCenter.getLogger(FindCommandParser.class)`!
Please import static for `getLogger(...)`.

2019-04-12 01:48 UTC, Creastery commented on src/main/java/pwe/planner/logic/parser/PlannerShowCommandParser.java
> +    private static final Logger logger = LogsCenter.getLogger(MainApp.class);
This should be `LogsCenter.getLogger(PlannerShowCommandParser.class)`!
Please import static for `getLogger(...)`.

2019-04-12 01:48 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/PlannerShowCommandTest.java
> +        String expectedMessage = String.format(PlannerShowCommand.MESSAGE_SUCCESS, 2);
Don't hardcode the value 2 here.
Instead, declare the `List` of semesters that will be displayed, and use `.size()` instead of `2`.
Same for the rest of the tests.

2019-04-12 01:48 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/PlannerShowCommandTest.java
> +                new SemesterContainsKeywordPredicate<>("1");
Should use the helper methods you created below.

2019-04-12 18:21 UTC, Creastery requested changes

2019-04-12 18:21 UTC, Creastery commented on src/test/java/pwe/planner/logic/parser/PlannerShowCommandParserTest.java
> +
Remove unnecessary newline here.

2019-04-12 18:21 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerShowCommand.java
> +        model.updateFilteredDegreePlannerList(predicate);
Add newline after `requireNonNull(model)` to separate pre-conditions from actual code.

2019-04-13 21:28 UTC, Creastery requested changes

2019-04-13 21:28 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerShowCommand.java
> +            + "specified based on year and/or semester\n"
I think you can remove the word `academic` from the entire PR to reduce formality.
Also, you didn't mention where this is shown.
Perhaps you can end off the sentence with: "year and/or semester in the degree plan.".

2019-04-13 21:28 UTC, Creastery commented on src/main/java/pwe/planner/logic/parser/BooleanExpressionParser.java
> +            "%1$s is not a valid parameter accepted by this command!";
What is `this` command?
I think it would be better to replace it with `%2$s` and then formatting the message with `XYZCommand.COMMAND_WORD`.

2019-04-14 06:51 UTC, Creastery approved these changes

2019-04-14 06:52 UTC, lycjackie approved these changes

2019-04-14 06:53 UTC, merged

2019-04-14 07:01 UTC, truegitnovice commented
Thanks for the reviews!