Logic: update 'planner_move' to handle co-requisites
CS2113-AY1819S2-T09-1/main pull request #197
Opened 2019-04-06 17:51 UTC by truegitnovice

The application allows the user to set co-requisites to modules. However, 'planner_move' does not handle co-requisites. Hence, the user has to move the codes that shares co-requisites manually.

Let's enhance 'planner_move' command by allowing it to handle co-requisites so that when a module is moved, its co-requisites are moved along if they exist in the degree plan.

2019-04-07 07:18 UTC, lycjackie requested changes

2019-04-07 07:18 UTC, lycjackie commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +                .append(corequisitesToMove.stream().map(Code::toString).collect(Collectors.joining(", ")));
Perhaps, instead of using a `StringBuilder` here, you might want to consider the following?
```
MESSAGE_SUCCESS = "Successfully moved %1$s to Year %2$s, Semester %3$s of degree planner\n"
                        + "Co-Requisite(s) moved along: %4$s"
coReqMoved = corequisitesToMove.stream().map(Code::toString).collect(Collectors.joining(", "));

String.format(MESSAGE_SUCCESS, toMove, destinationYear, destinationSemester, coRedMoved);
```

2019-04-07 07:18 UTC, lycjackie commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +                String.format(MESSAGE_SUCCESS, codesMoved.toString()));
Do you think you can change this to 1 line? This line looks shorter than the previous thou.

No reason to split it

2019-04-07 07:18 UTC, lycjackie commented on src/test/java/pwe/planner/logic/commands/PlannerMoveCommandTest.java
> +                model.getApplication().getDegreePlannerList().stream()
Can you join this line with L89? It does not look like it will reach the line limit.

2019-04-07 07:18 UTC, lycjackie commented on src/test/java/pwe/planner/logic/commands/PlannerMoveCommandTest.java
> +                String.format(PlannerMoveCommand.MESSAGE_SUCCESS,
Same as above comment

2019-04-07 07:18 UTC, lycjackie commented on src/test/java/pwe/planner/logic/commands/PlannerMoveCommandTest.java
> +                model.getApplication().getDegreePlannerList().stream()
Same as above comment

2019-04-07 07:18 UTC, lycjackie commented on src/test/java/pwe/planner/logic/commands/PlannerMoveCommandTest.java
> +    private String codesMovedContent(Code code, Year year, Semester semester, Set<Code> corequisites) {
Maybe if you used the format string style, this method could be reduced accordingly?

2019-04-07 19:18 UTC, lycjackie reviewed
LGTM,

I will be tagging @Creastery on the Model part. 

Great work!

2019-04-07 20:29 UTC, Creastery requested changes

2019-04-07 20:29 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            + "in a degree plan.\n"
Maybe it would be good to mention "move ... to another year/semester of the degree plan".

2019-04-07 20:29 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            + "degree planner!\n" + "Co-Requisite(s) moved along: %4$s";
Let's standardise the success message to be:
"Successfully moved ...."

2019-04-07 20:29 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            + "degree planner!\n" + "Co-Requisite(s) moved along: %4$s";
If the module has no co-requisites, `%4$s` will be blank as you didn't handle a blank string for `%4$s` below.

2019-04-07 20:29 UTC, Creastery commented on src/main/java/pwe/planner/model/Application.java
> +        if (target.getCodes().size() > editedDegreePlanner.getCodes().size()) {
Why not just check if `target.getCodes().equals(editedDegreePlanner.getCodes())`?

2019-04-07 20:29 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/PlannerMoveCommandTest.java
> +                        corequisitesMoved);
Make this statement 2 lines instead.

2019-04-08 04:31 UTC, truegitnovice commented on src/main/java/pwe/planner/model/Application.java
> +        if (target.getCodes().size() > editedDegreePlanner.getCodes().size()) {
Thank you for the suggesting the improvement that can be made. Changes made.

2019-04-11 03:00 UTC, Creastery requested changes

2019-04-11 03:00 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/PlannerMoveCommandTest.java
> +                String.format(PlannerMoveCommand.MESSAGE_UNAVAILABLE_SEMESTER, validSemester));
Here, you are supplying the expected message, which is an error message.
Yet, Line 175 suggests that this test is supposed to be successful!

2019-04-11 03:00 UTC, Creastery commented on src/test/java/pwe/planner/logic/commands/PlannerMoveCommandTest.java
> +        assertCommandFailure(new PlannerMoveCommand(validYear, validSemester, unavailableValidCodeToMove), model,
You didn't use `plannerMoveCommand` variable as first argument to `assertCommandFailure`!

2019-04-11 03:00 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +        model.moveModuleBetweenPlanner(sourcePlanner, destinationPlanner, toMove);
You didn't check if all the co-requisites to be moved have the target semester offered before you call this method!

2019-04-11 03:00 UTC, Creastery commented on src/main/java/pwe/planner/model/Application.java
> +                .collect(Collectors.toSet());
This means you are ignoring co-requisite modules that are not offered the semester you are trying to move the modules to.

But, if the modules are co-requisites, they all need to be offered in the same semester.
In other words, if a module has a co-requisite that is not offered in the semester to move to, all these modules cannot be moved to the same semester (all are co-requisites of each other).

2019-04-12 18:07 UTC, Creastery requested changes

2019-04-12 18:07 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            + "Perhaps you may want to check the module list for the semester(s) the module is offered in.";
There should be `.\n` after `%1$s`.

2019-04-12 18:07 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            "You cannot move a module that has co-requisite(s) %1$s not offered in Semester %2$s"
There should be `.\n` after `%2$s`.

```
that has co-requisite(s) %1$s not offered
```
can be rephrased to:
```
that has co-requisite(s) %1$s, which isn't not offered
```

2019-04-12 18:07 UTC, Creastery commented on src/test/java/pwe/planner/testutil/TypicalModules.java
> +            .withSemesters("1")
What's the rationale for this change?

2019-04-13 04:24 UTC, truegitnovice commented on src/test/java/pwe/planner/testutil/TypicalModules.java
> +            .withSemesters("1")
This change is have been made to include the test case where module is available on Semester 2 but co-requisite is not and output message for that case accordingly.

2019-04-13 04:30 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            "You cannot move a module that has co-requisite(s) %1$s not offered in Semester %2$s"
> There should be `.\n` after `%2$s`.
> 
> ```
> that has co-requisite(s) %1$s not offered
> ```
> can be rephrased to:
> 
> ```
> that has co-requisite(s) %1$s, which isn't not offered
> ```
Thanks for the suggestion. I have changed as below accordingly since I believe `not` here is added unexpectedly.
```
that has co-requisite(s) %1$s, which isn't offered
```

2019-04-13 04:33 UTC, truegitnovice commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            + "Perhaps you may want to check the module list for the semester(s) the module is offered in.";
Thanks for pointing!

2019-04-13 21:59 UTC, Creastery requested changes

2019-04-13 21:59 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            + " available in the application!";
How does looking at the semesters available in the application help the user to be able to move the module to the Semester?

2019-04-13 21:59 UTC, Creastery commented on src/main/java/pwe/planner/logic/commands/PlannerMoveCommand.java
> +            + " available in the application!";
How?

2019-04-14 09:50 UTC, Creastery approved these changes
Please see minor changes that needs to be done below. Thanks!

2019-04-14 09:53 UTC, Creastery requested changes

2019-04-14 09:53 UTC, Creastery commented on src/main/java/pwe/planner/model/Application.java
> +            degreePlanners.setDegreePlanner(sourceDegreePlanner, editedSourcePlanner);
You can remove `degreePlanners` here to utilise `Application#setDegreePlanner(...)` instead!

2019-04-14 09:53 UTC, Creastery commented on src/main/java/pwe/planner/model/Application.java
> +        degreePlanners.setDegreePlanner(targetDestinationPlanner, editedDestinationPlanner);
You can remove `degreePlanners` here to utilise `Application#setDegreePlanner(...)` instead!

2019-04-14 10:18 UTC, Creastery approved these changes

2019-04-14 10:18 UTC, Creastery commented
LGTM. Approving and merging.

2019-04-14 10:19 UTC, lycjackie approved these changes

2019-04-14 10:19 UTC, merged