DeveloperGuide: add planner-related details
CS2113-AY1819S2-T09-1/main pull request #24
Opened 2019-02-27 07:54 UTC by WendyBaiYunwei

2019-02-27 08:17 UTC, Letm3through requested changes

2019-02-27 08:17 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +|`* *` |user |edit my module plan|update my plan if there is any change in my current plan
Please remove the repeated user stories.
Also take a look at your parts in google docs

2019-02-27 08:17 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +=== Use case: Generate a module planner table
I believe these are my points.
Maybe do you wanna stick to your tasks.
Refer to the google docs last page

2019-02-27 08:17 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> -By: `Team T09-1`      Since: `Feb 2019`      Licence: `MIT`
May I know what you change here if you did?

2019-02-27 08:19 UTC, Letm3through reviewed
Please add commit message to describe what you have done

2019-02-27 15:53 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +1.  Student requests to change their module planner
What do you mean?

2019-02-27 15:55 UTC, Creastery commented on docs/DeveloperGuide.adoc
> +2.  Application prompts students to enter the changes, which can either be changing the time to take a module, resetting the restriction or saving and exiting. If student chooses save and exit, the a
The second sentence should be included as an extension to the MSS.

2019-03-02 01:47 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> +|`* *` |user |edit my module plan|update my plan if there is any change in my current plan
sorry where is the repeated part?

2019-03-02 01:47 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> -By: `Team T09-1`      Since: `Feb 2019`      Licence: `MIT`
I did not change. the line is still there

2019-03-02 05:08 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> -By: `Team T09-1`      Since: `Feb 2019`      Licence: `MIT`
I did not delete the line

2019-03-02 12:16 UTC, Letm3through requested changes
Could you squash the commits after editing? Thank you for updating

2019-03-02 12:16 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
>  |Priority |As a ... |I want to ... |So that I can...
@Creastery Do we have to remove all user stories that are not in v1.1?

2019-03-02 12:16 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> ++
Can we be consistent and use "PlanWithEase" instead of "Degree planner" or "Application" or "The application"?

2019-03-02 12:17 UTC, Creastery commented on docs/DeveloperGuide.adoc
>  |Priority |As a ... |I want to ... |So that I can...
No. We can keep it.

2019-03-02 12:24 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> ++
I can change application to planwithease, but I think degree planner is necessary

2019-03-02 12:25 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> ++
otherwise ppl won't know it is specifically "degree planner"

2019-03-02 12:31 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> ++
As I believe that "application" and "PlanWithEase" are equivalent, maybe I will just keep the use cases consistent through the use of "application" since it is already there

2019-03-02 12:32 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
>  |Priority |As a ... |I want to ... |So that I can...
I think squashing of commits is available only before pushing. I will look into this

2019-03-02 12:36 UTC, Letm3through requested changes

2019-03-02 12:36 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +Category is static! Only from "University Level Requirements/Computing Foundation/Information Security Requirements/Computing Breadth/IT Professionalism/Mathematics"
Please Rephrase this part

2019-03-02 12:36 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> +* 3a. The input is invalid.
Perhaps something like:
 3a. "User input incorrect format."
3a1.PlanWithEase Shows an error message

Also note, the application accepts delete INDEX

2019-03-02 12:37 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
>  |Priority |As a ... |I want to ... |So that I can...
You can squash after pushing. After squash, you can push by force push.

2019-03-02 12:41 UTC, truegitnovice commented on docs/DeveloperGuide.adoc
> ++
Note "degree planner" is **not** the one deleting the module. 
It is "PlanWithEase" (Application) deleting the module.
I recommend using the term "PlanWithEase" throughout to make the terms clearer.

2019-03-03 01:00 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> ++
let me show an example:
for usecase: add module to degree planner, here is the original version
1.  User requests to list modules in degree planner
2.  Degree planner shows the list of modules
3.  User requests to add a specific module in the list
4.  Degree planner adds the module

if you replace degree planner with PlanWithEase, it will become
1.  User requests to list modules in PlanWithEase
2.  PlanWithEase shows the list of modules
3.  User requests to add a specific module in the list
4.  PlanWithEase adds the module

Hope this clarifies what i mean

2019-03-03 05:39 UTC, Creastery commented on docs/DeveloperGuide.adoc
> ++
@truegitnovice @WendyBaiYunwei 
The term `Application` should be used.
See the note at Appendix D:
For all use cases below, the *System* is the `AddressBook` and the *Actor* is the `user`, unless specified otherwise)

2019-03-03 08:42 UTC, WendyBaiYunwei commented on docs/DeveloperGuide.adoc
> ++
@Creastery 
So do i replace degree planner with application as well?
If so, how do I show that the system is specifically degree planner under the application?

2019-03-03 11:28 UTC, Creastery commented on docs/DeveloperGuide.adoc
> ++
@WendyBaiYunwei 
Let me set this straight so that there's no confusion:
For Appendix D, all the interaction with the system should be with the 'Application'.

I amended your use case above as an example:
1. User requests to list modules in the Application
2. Application shows the list of modules
3. User requests to adds a module into the Application's degree planner
4. Application adds the module into the degree planner (and...)

2019-03-05 05:58 UTC, truegitnovice commented
Closing in favor of other PR [#61](https://github.com/CS2113-AY1819S2-T09-1/main/pull/61)

2019-03-05 05:58 UTC, closed without merging