UserGuide: add planner-related details
CS2113-AY1819S2-T09-1/main pull request #25
Opened 2019-02-27 08:03 UTC by WendyBaiYunwei

2019-02-27 15:39 UTC, Creastery requested changes
Previewing the changes [here](https://github.com/cs2113-ay1819s2-t09-1/main/blob/67f5f15ede7c18690dbdc5f9c1b576dbf84f474e/docs/UserGuide.adoc), it does look like there's a lot of formatting issues.

For instance, the `e.g.` for `planner`-related commands in the [Command Summary](https://github.com/cs2113-ay1819s2-t09-1/main/blob/67f5f15ede7c18690dbdc5f9c1b576dbf84f474e/docs/UserGuide.adoc#5-command-summary) are not on new lines.

Also, the command titles and descriptions are a bit repetitive. 
I was expecting the titles to be more concise, and have greater details in the command descriptions.
 
We need to take into consideration that this is a **User Guide**, and so we should go into the details by explaining what each command does, and how a user can perform certain actions.

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +Format: `planner add MODULE_CODE`
Which `semester` will the `module` be added to by the planner?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +Format: `planner edit MODULE_CODE SEMESTER`
Is this supposed to be `planner move` instead of `planner edit`?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +* `planner move CS1231 Y1S2`
How should modules to be taken in Special Terms be added?
Can you provide some examples?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
If a module is exempted, is it supposed to show up in the planner (sentence above seems to suggest so)?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
"Toggling" an existing `module` in the `planner` doesn't sound intuitive.
Additionally, `planner exempt` seems to suggest to add a `module` exemption only, not toggle/remove a `module` exemption.

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +Displays a list of modules that can be taken in the current selected semester
This command description is very vague. Could you elaborate further with examples?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Displaying the entire module planner : `planner list`
This command description is very vague. Could you elaborate further with examples?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Displaying the entire module planner in tree format : `planner list-tree`
This command description is very vague. Could you elaborate further with examples?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +* *Planner susggest* : `planner suggest`
`susggest` -> `suggest`

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +* `planner exempt CS1231`
Perhaps it would be better to implement this `exempt` feature by creating a parameter when adding a `module`, and allow editing a `module` to update this `exempt` flag.

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Displaying the entire module planner : `planner list`
What is the default view for the planner?

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +===  Auto-generating the entire module plan and display the result : `planner generate`
Please avoid pleonasm by removing `auto`.

2019-02-27 15:39 UTC, Creastery commented on docs/UserGuide.adoc
> +Auto-generates the entire module plan and display the result
What does it mean to `generate` a module plan? 
Are there any constraints that is considered in doing so?
How is the the `plan` generated?

2019-02-27 15:52 UTC, Creastery commented on docs/UserGuide.adoc
> +Auto-generates the entire module plan and display the result
I am confused after reading this portion of the `DeveloperGuide` amendments you made in PR #24:
```
*MSS*
1.  Student requests to get a system-generated module planner
2.  Application prompts students to select their restrictions
3.  Student enters required details
4.  Application sets the module planner according to programme requirements and restrictions.
5.  Application shows the module planner

Use case ends.

*Extensions*

[none]
Students have already keyed in their restrictions in step 1

Use case directly jumps to step 5
```

1. What are the `restrictions`?
2. What does `application sets the module planner...` mean?

2019-03-01 07:37 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
yes. But I don't think it needs to be shown in userguide?

2019-03-01 08:04 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +* `planner exempt CS1231`
type exempt once to exempt a mod. type again to remove the exemption. is it ok?

2019-03-01 09:36 UTC, Creastery commented on docs/UserGuide.adoc
> +* `planner exempt CS1231`
@lycjackie @truegitnovice @chyeo @WendyBaiYunwei 
As mentioned, it is more logical to implement exemption a command of `module` rather than a command of `planner`. Can I get the rest to share their thoughts on this matter as well?

2019-03-01 09:42 UTC, lycjackie commented on docs/UserGuide.adoc
> +* `planner exempt CS1231`
I believe is more logical for `exemption` to be part of `module`

This is because we want to isolate all functions related to the `module` itself.

As such, the `planner` should only read an `immutable` view of the module. 
i.e. planner does not have a direct modification of any `module` objects. 

This would keep the code cleaner i guess.

2019-03-01 09:45 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
Looking at the updated UI mockup in PR #31, my understanding is that the planner will replace the `BrowserPanel` (bottom right panel) to provide an outline of the degree modules grouped by their respective Years/Semesters.

I would think that a user would want to be able to add modules that he/she has yet to take into the planner. 

Is there any use case for a user that wants to be able to see modules that he/she is exempted from within the planner when this information is available and shown in the `ModuleListPanel` (left sidebar).

2019-03-01 09:46 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
> yes. But I don't think it needs to be shown in userguide?

This needs to be clearly reflected in the User Guide. 
Otherwise, how would a user know and understand what each command does?

2019-03-01 11:22 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
sorry I didn't quite get what you meant. So you are asking me to elaborate this part with some notes, stating that the exemption will be shown in the planner?

2019-03-01 11:25 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +* `planner exempt CS1231`
so I just delete this from my part right?

2019-03-01 11:49 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
I think this `planner exempt` command needs some serious re-evaluation.

The main considerations I have are as follows:
1. How are exempted modules shown and conveyed to the user in the planner?
2. Is there a need to create an `planner exempt` command, or should we be moving it to `module exempt`?
3. If the `ModuleListPanel` sidebar is already showing this, why are duplicating the available information to show it within the planner (replaces bottom-right `BrowserPanel`)?
4. The User Guide is meant to be beginner-friendly, and provide help to new users to understand the command easily. If the command description is vague, then it defeats the purpose of the User Guide.

Please work with @truegitnovice to think through how this is to be done. 
In the meantime, let's delay this particular feature to v1.2 milestone.

2019-03-01 12:16 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
I personally believe that the exempt command should be under module exempt. and there is no need to show exempted mods in the planner. I will discuss with @truegitnovice

2019-03-01 12:19 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
but tree format should show exempted mods

2019-03-02 06:53 UTC, Creastery requested changes
Why are the following command and descriptions removed?
```
planner move
planner list
planner list-tree
planner suggest
planner generate
planner exempt
```

So far, I understand from our discussions that implementing `planner generate` takes a lot of time, and we might not be able to finish it by v1.4. Since it is not a core feature of our application, we can choose to include this as a v2.0 feature.

As for `planner exempt`, we are treating it as part of `module add/edit`.

Update: Discussed with Yunwei. She removed the remaining as it is not within her scope, so I'm proceeding to resolve this comment.

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +* `SEMESTER` is in the format `YyearSsem[s]`, with `year` indicating the year, `sem` indicating the semester and `[s]` indicating whether the semester is a special semester.`year` must be a positive
Can you move the explanation of each argument to a new line?

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +Format: `planner add MODULE_CODE SEMESTER`
Please change this to `planner add MODULE_CODE y/YEAR s/SEMESTER` to be consistent with the rest of the command usage.

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +* *Planner add* : `planner add MODULE SEMESTER` +
Can we rename this to: `Add module to Degree Planner`?

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +* *Planner delete* : `planner delete` +
Can we rename this to: `Delete module from Degree Planner`?

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Adding a module to the planner : `planner add`
Can we rename this to: `Adding a module to the degree planner`?

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds an existing module to the planner. +
`planner` -> `degree planner`

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +Adds module CS1231 to year 1 semester 2.
After adding, shouldn't the UI update to reflect the changes in the degree planner?

2019-03-02 06:53 UTC, Creastery commented on docs/UserGuide.adoc
> +Deleting an existing module from the planner. +
`planner` -> `degree planner`

2019-03-02 11:19 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +* *Planner add* : `planner add MODULE SEMESTER` +
you mean the command?

2019-03-02 12:55 UTC, Creastery requested changes

2019-03-02 12:55 UTC, Creastery commented on docs/UserGuide.adoc
> +Format: `planner add MODULE_CODE y/YEARs/SEM[/s]`
I thought there was an agreement to use `y/YEAR s/SEMESTER` as the format already?
Doing this will require custom parsing, which goes against the style of how the rest of the commands work.

2019-03-02 12:55 UTC, Creastery commented on docs/UserGuide.adoc
> +* `[/s]` indicates whether the semester is a special semester. When `/s` is added, it is a special semester, vice versa.
I think for v1.1 milestone there are two approach we can adopt:
1. Do not support special terms
2. Support special terms by using Semester 3/4.

In PR #34, option (2) is chosen.

Why is there discrepancy in User Guide and actual implementation?
Please discuss with @truegitnovice before fixing this.

2019-03-02 12:55 UTC, Creastery commented on docs/UserGuide.adoc
> +* `YEAR` must be a positive integer lower than 7, and `SEM` must be either 1 or 2.
Likewise, the range of values supported doesn't seem to match PR #34.

2019-03-02 12:55 UTC, Creastery commented on docs/UserGuide.adoc
> +Format: `planner move MODULE_CODE y/YEARs/SEM[/s]`
Same as previous.

2019-03-02 12:55 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Using planner to suggest modules to take: `planner suggest`
Is this going to be implemented in v1.1?

2019-03-03 00:45 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Using planner to suggest modules to take: `planner suggest`
no. i was just moving my part from the google docs to here

2019-03-03 00:48 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +* `[/s]` indicates whether the semester is a special semester. When `/s` is added, it is a special semester, vice versa.
I adopted my approach because semester 3/4 is not intuitive since NUS does not call it semester 3/4. @truegitnovice do you mind changing your part?

2019-03-03 07:17 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Using planner to suggest modules to take: `planner suggest`
If it's not implemented in v1.1, then when will it be implemented by?

2019-03-03 07:20 UTC, Creastery commented on docs/UserGuide.adoc
> +* `[/s]` indicates whether the semester is a special semester. When `/s` is added, it is a special semester, vice versa.
Please see my comment above on the concerns I have with the parsing of arguments.

2019-03-03 09:01 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
> but tree format should show exempted mods

Why?

2019-03-03 10:15 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Toggling an existing module in the planner to be exempted: `planner exempt MODULE_CODE`
I thought showing the exempted modules in tree format could make the pre-requisites relationship clearer. anyway, I'm not in charge of this

2019-03-03 10:19 UTC, WendyBaiYunwei commented on docs/UserGuide.adoc
> +=== Using planner to suggest modules to take: `planner suggest`
it's not stated in the google docs. is it ok to implement it by v1.3?

2019-03-03 14:29 UTC, Creastery commented on docs/UserGuide.adoc
> +=== Using planner to suggest modules to take: `planner suggest`
As corresponded, this needs to be implemented by v1.2 unless there's strong reasons not to.

2019-03-03 15:34 UTC, Creastery approved these changes
LGTM. Approving and merging.

2019-03-03 15:38 UTC, merged