Add Planner Model
CS2113-AY1819S2-T09-1/main pull request #34
Opened 2019-03-02 04:39 UTC by truegitnovice

Since we do not have a model for Planner

Let's create a model for Planner

2019-03-02 21:39 UTC, Creastery requested changes
Thanks for the effort! There are a few inconsistencies in this large PR.
I have left some comments, so do fix them accordingly.
In particular, please note the important comment on `SampleDegreePlannerUtil`.
You likely need to refine the model further as mentioned.

Let me know if you need any clarifications.

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/planner/DegreePlannerSemester.java
>       * Returns true if a given string is a valid date.
`date` -> `semester`

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/planner/DegreePlannerYear.java
> +public class DegreePlannerYear {
This class should be called `Year`!

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/planner/DegreePlannerYear.java
> +    public final String plannerYear;
`plannerYear` -> `year`

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/planner/DegreePlannerSemester.java
> +            "Semester should only be given in S (e.g. 1) format and in valid form.";
This needs to be rephrased to better explain the constraints.

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/DegreePlannerModel.java
> +public interface DegreePlannerModel {
Refer to comment on `Model extends DegreePlannerModel`.

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/Model.java
> +public interface Model extends DegreePlannerModel {
It is strange for `Model` to extend `DegreePlannerModel`.
Additionally, you updated `Model` class to pretty much include what `DegreePlannerModel` has already!
I think `DegreePlannerModel` is redundant here.

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/util/SampleDegreePlannerUtil.java
> +                    new DegreePlannerSemester("1")),
This doesn't make sense.
If a `DegreePlanner` simply contains `Code`, `Year` and `Semester`, why isn't `Year` and `Semester` part of `Module`?
This makes collating the list of modules for a particular year & semester difficult as well.

To improve the `DegreePlanner` model further, I suggest the following:
```java
DegreePlanner Y1_S1 = new DegreePlanner(new Year("1"), new Semester("1"));
Y1_S1.addCode(new Code("CS1010")).addCode(new Code("CS1231")).addCode(new Code("MA1101R"))
     .addCode(new Code("GER1000"));
```

You can make `UniqueDegreePlannerList` more intuitive by checking if the combination of `Year` and `Semester`  is unique (instead of `Code` being unique).

By doing so, we achieve a cleaner JSON storage data file as well:
```json
{
	"planner": [{
		"year": "1",
		"semester": "1",
		"modules": ["CS1010", "CS1231", "MA1101R", "GER1000"]
	}, {
		"year": "1",
		"semester": "2",
		"modules": ["..."]
	}]
}
```

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/MainApp.java
> +            initalDegreePlannerListData = new DegreePlannerList();
Why aren't we returning `SampleDegreePlannerUtil::getSampleDegreePlannerList` instead?

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/MainApp.java
> +            initalDegreePlannerListData = new DegreePlannerList();
Why aren't we returning `SampleDegreePlannerUtil::getSampleDegreePlannerList` instead?

2019-03-02 21:39 UTC, Creastery commented on src/main/java/seedu/address/model/util/SampleDegreePlannerUtil.java
> +                    new DegreePlannerSemester("1")),
Adding on to my previous point above, since there is no way for the user to add/edit/delete the degree planner, `SampleDegreePlannerUtil#getSampleDegreePlanners()` needs to include all valid Year + semesters for users to be able to add module codes to the respective year/semesters!

2019-03-03 03:28 UTC, truegitnovice commented on src/main/java/seedu/address/MainApp.java
> +            initalDegreePlannerListData = new DegreePlannerList();
Is it better to return SampleDegreePlannerList for all problems dealing with the files?
I think we can just return SampleDegreePlannerList only when the file is missing so I didn't return it at elsewhere.

2019-03-03 05:32 UTC, Creastery commented on src/main/java/seedu/address/MainApp.java
> +            initalDegreePlannerListData = new DegreePlannerList();
My understanding is this:
Although it is a norm to return an empty list on an exception, the users currently do not have an option to amend the list of Year/Semesters (e.g. Y1S1, Y1S2, Y1S3, Y1S4, Y2S1, ..., Y4S4).
In that case, we should return `SampleDegreePlannerUtil::getSampleDegreePlannerList` on exception so that this degree planner feature can still be used even when there's an exception!

2019-03-03 07:57 UTC, Creastery requested changes
Great work so far!
Please fix the problem I've mentioned. Thanks!

2019-03-03 07:57 UTC, Creastery commented on src/main/java/seedu/address/storage/JsonDegreePlannerListStorage.java
> +    public void saveDegreePlannerList(ReadOnlyDegreePlannerList degreePlannerList) throws IOException {
This function is never invoked during the application lifespan.
I think you need to trigger it explicitly in `LogicManager#execute(...)`

2019-03-03 09:19 UTC, Creastery commented on src/main/java/seedu/address/model/ModelManager.java
> +    private final VersionedDegreePlannerList versionedDegreePlannerList;
As discussed, I am accepting this approach for v1.1 milestone.
However, let's aim to combine this with `VersionedAddressBook` by v1.3 milestone.

2019-03-03 09:21 UTC, truegitnovice commented on src/main/java/seedu/address/model/ModelManager.java
> +    private final VersionedDegreePlannerList versionedDegreePlannerList;
Okay Tks!

2019-03-03 10:09 UTC, Creastery approved these changes
LGTM. Thanks for the great work!

I'm going to approve and merge accordingly. However, please note that our coverage has decreased significantly. Please work on improve our code coverage by v1.3.

Likewise with PR #43, this PR also grew way larger than the original intent.
Please try to avoid large PRs to implement multiple functionalities at one go next time.

2019-03-03 10:14 UTC, merged

2019-03-03 10:30 UTC, truegitnovice commented
Thank you for approving. Also, thank you for the great reviews!