Model combine degree planner
CS2113-AY1819S2-T09-1/main pull request #75
Opened 2019-03-14 06:58 UTC by truegitnovice

In the current implementation, DegreePlanner class has its own VersionedDegreePlannerList class.

Let's make changes to combine VersionedDegreePlannerList into VersionedAddressBook so that it would be more logical for the application flow and architecture.

2019-03-22 18:12 UTC, Creastery requested changes
Changes looks good to me so far. Please see minor change requested.
Thanks!

2019-03-22 18:12 UTC, Creastery commented on src/test/java/seedu/address/testutil/TypicalDegreePlanners.java
> +        return new ArrayList<>(Arrays.asList(YEAR_1_SEMESTER_1, YEAR_1_SEMESTER_2, YEAR_2_SEMESTER_1, YEAR_2_SEMESTER_2,
Can you add some sample code in degree planners in `TypicalDegreePlanners` so that it is actually "typical".
Remember to update the `typicalDegreePlannerAddressBook.json` file as well!

2019-03-23 01:27 UTC, truegitnovice commented on src/test/java/seedu/address/testutil/TypicalDegreePlanners.java
> +        return new ArrayList<>(Arrays.asList(YEAR_1_SEMESTER_1, YEAR_1_SEMESTER_2, YEAR_2_SEMESTER_1, YEAR_2_SEMESTER_2,
Thanks for the review. I have made the changes by adding codes to Year 1 Semester 1 of `TypicalDegreePlanners`. I have updated the changes accordingly on `typicalDegreePlannerAddressBook.json`.

2019-03-24 12:03 UTC, Creastery requested changes
Please see minor checkstyle issues to resolve.
Avoid unnecessary newlines / indentations.

Thanks!

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/ClearCommandTest.java
> +                        .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/ClearCommandTest.java
> +                                .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
> +                new ModelManager(model.getAddressBook(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/EditCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RedoCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/RedoCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/SelectCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/SelectCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/UndoCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/logic/commands/UndoCommandTest.java
> +                            .toModelType(), new UserPrefs());
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/model/AddressBookTest.java
> +                        getTypicalRequirementCategoriesList())
Please fix unnecessary indentations.

2019-03-24 12:03 UTC, Creastery commented on src/test/java/seedu/address/model/ModelManagerTest.java
> +                new ModelManager(addressBook, userPrefs);
Please fix unnecessary indentations.

2019-03-25 05:11 UTC, Creastery approved these changes
LGTM. Approving and merging.
Thanks for cleaning up the model as requested!

2019-03-25 05:19 UTC, merged

2019-03-25 05:19 UTC, truegitnovice commented
Thank you for the amazing review!